use cairo_air::pedersen::air::{Claim, PedersenContextClaim};
use stwo::prover::backend::simd::SimdBackend;
use tracing::{span, Level};

use crate::witness::components::{
    memory_id_to_big, partial_ec_mul_window_bits_18, pedersen_aggregator_window_bits_18,
    pedersen_points_table_window_bits_18, range_check_20, range_check_8, range_check_9_9,
};
use crate::witness::prelude::ComponentTrace;
use crate::witness::utils::TreeBuilder;

/// Holds all traces generated by pedersen context (for parallel execution).
pub struct PedersenContextTraces {
    pub pedersen_aggregator_trace: ComponentTrace<
        { cairo_air::components::pedersen_aggregator_window_bits_18::N_TRACE_COLUMNS },
    >,
    pub partial_ec_mul_trace:
        ComponentTrace<{ cairo_air::components::partial_ec_mul_window_bits_18::N_TRACE_COLUMNS }>,
    pub pedersen_points_table_trace: ComponentTrace<
        { cairo_air::components::pedersen_points_table_window_bits_18::N_TRACE_COLUMNS },
    >,
}

/// Generate pedersen context traces without extending to tree_builder (for parallel execution).
#[allow(clippy::too_many_arguments)]
pub fn pedersen_context_write_trace_gen(
    pedersen_aggregator_trace_generator: Option<pedersen_aggregator_window_bits_18::ClaimGenerator>,
    partial_ec_mul_trace_generator: Option<partial_ec_mul_window_bits_18::ClaimGenerator>,
    pedersen_points_table_trace_generator: Option<
        pedersen_points_table_window_bits_18::ClaimGenerator,
    >,
    memory_id_to_big_state: Option<&memory_id_to_big::ClaimGenerator>,
    rc_8_trace_generator: Option<&range_check_8::ClaimGenerator>,
    rc_9_9_trace_generator: Option<&range_check_9_9::ClaimGenerator>,
    rc_20_trace_generator: Option<&range_check_20::ClaimGenerator>,
) -> (
    Option<PedersenContextTraces>,
    PedersenContextClaim,
    PedersenContextInteractionClaimGenerator,
) {
    let span = span!(Level::INFO, "write pedersen context trace").entered();
    if pedersen_aggregator_trace_generator
        .as_ref()
        .is_none_or(|tg| tg.is_empty())
    {
        return (
            None,
            PedersenContextClaim { claim: None },
            PedersenContextInteractionClaimGenerator { gen: None },
        );
    }

    let pedersen_aggregator_trace_generator = pedersen_aggregator_trace_generator
        .expect("Should have pedersen aggregator trace generator at this point");
    let mut partial_ec_mul_trace_generator = partial_ec_mul_trace_generator
        .expect("Should have partial EC mul trace generator at this point");
    let pedersen_points_table_trace_generator = pedersen_points_table_trace_generator
        .expect("Should have pedersen points table trace generator at this point");

    // pedersen_aggregator.write_trace adds inputs to partial_ec_mul (dependency)
    let (pedersen_aggregator_trace, pedersen_aggregator_claim, pedersen_aggregator_interaction_gen) =
        pedersen_aggregator_trace_generator.write_trace(
            memory_id_to_big_state.unwrap(),
            rc_8_trace_generator.unwrap(),
            &mut partial_ec_mul_trace_generator,
        );

    // Use write_trace_gen to get trace without extending
    let (partial_ec_mul_trace, partial_ec_mul_claim, partial_ec_mul_interaction_gen) =
        partial_ec_mul_trace_generator.write_trace_gen(
            &pedersen_points_table_trace_generator,
            rc_9_9_trace_generator.unwrap(),
            rc_20_trace_generator.unwrap(),
        );

    let (
        pedersen_points_table_trace,
        pedersen_points_table_claim,
        pedersen_points_table_interaction_gen,
    ) = pedersen_points_table_trace_generator.write_trace();
    span.exit();

    let traces = PedersenContextTraces {
        pedersen_aggregator_trace,
        partial_ec_mul_trace,
        pedersen_points_table_trace,
    };
    let claim = Some(Claim {
        pedersen_aggregator: pedersen_aggregator_claim,
        partial_ec_mul: partial_ec_mul_claim,
        pedersen_points_table: pedersen_points_table_claim,
    });
    let gen = Some(PedersenInteractionClaimGenerator {
        pedersen_aggregator_interaction_gen,
        partial_ec_mul_interaction_gen,
        pedersen_points_table_interaction_gen,
    });
    (
        Some(traces),
        PedersenContextClaim { claim },
        PedersenContextInteractionClaimGenerator { gen },
    )
}

/// Extend pedersen context traces to tree_builder.
pub fn extend_pedersen_context_traces(
    traces: PedersenContextTraces,
    tree_builder: &mut impl TreeBuilder<SimdBackend>,
) {
    tree_builder.extend_evals(traces.pedersen_aggregator_trace.to_evals());
    tree_builder.extend_evals(traces.partial_ec_mul_trace.to_evals());
    tree_builder.extend_evals(traces.pedersen_points_table_trace.to_evals());
}

pub fn pedersen_context_write_trace(
    pedersen_aggregator_trace_generator: Option<pedersen_aggregator_window_bits_18::ClaimGenerator>,
    partial_ec_mul_trace_generator: Option<partial_ec_mul_window_bits_18::ClaimGenerator>,
    pedersen_points_table_trace_generator: Option<
        pedersen_points_table_window_bits_18::ClaimGenerator,
    >,
    tree_builder: &mut impl TreeBuilder<SimdBackend>,
    memory_id_to_big_state: Option<&memory_id_to_big::ClaimGenerator>,
    rc_8_trace_generator: Option<&range_check_8::ClaimGenerator>,
    rc_9_9_trace_generator: Option<&range_check_9_9::ClaimGenerator>,
    rc_20_trace_generator: Option<&range_check_20::ClaimGenerator>,
) -> (
    PedersenContextClaim,
    PedersenContextInteractionClaimGenerator,
) {
    let span = span!(Level::INFO, "write pedersen context trace").entered();
    if pedersen_aggregator_trace_generator
        .as_ref()
        .is_none_or(|tg| tg.is_empty())
    {
        return (
            PedersenContextClaim { claim: None },
            PedersenContextInteractionClaimGenerator { gen: None },
        );
    }

    let pedersen_aggregator_trace_generator = pedersen_aggregator_trace_generator
        .expect("Should have pedersen aggregator trace generator at this point");
    let mut partial_ec_mul_trace_generator = partial_ec_mul_trace_generator
        .expect("Should have partial EC mul trace generator at this point");
    let pedersen_points_table_trace_generator = pedersen_points_table_trace_generator
        .expect("Should have pedersen points table trace generator at this point");

    let (pedersen_aggregator_trace, pedersen_aggregator_claim, pedersen_aggregator_interaction_gen) =
        pedersen_aggregator_trace_generator.write_trace(
            memory_id_to_big_state.unwrap(),
            rc_8_trace_generator.unwrap(),
            &mut partial_ec_mul_trace_generator,
        );
    tree_builder.extend_evals(pedersen_aggregator_trace.to_evals());
    let (partial_ec_mul_claim, partial_ec_mul_interaction_gen) = partial_ec_mul_trace_generator
        .write_trace(
            tree_builder,
            &pedersen_points_table_trace_generator,
            rc_9_9_trace_generator.unwrap(),
            rc_20_trace_generator.unwrap(),
        );
    let (
        pedersen_points_table_trace,
        pedersen_points_table_claim,
        pedersen_points_table_interaction_gen,
    ) = pedersen_points_table_trace_generator.write_trace();
    tree_builder.extend_evals(pedersen_points_table_trace.to_evals());
    span.exit();

    let claim = Some(Claim {
        pedersen_aggregator: pedersen_aggregator_claim,
        partial_ec_mul: partial_ec_mul_claim,
        pedersen_points_table: pedersen_points_table_claim,
    });
    let gen = Some(PedersenInteractionClaimGenerator {
        pedersen_aggregator_interaction_gen,
        partial_ec_mul_interaction_gen,
        pedersen_points_table_interaction_gen,
    });
    (
        PedersenContextClaim { claim },
        PedersenContextInteractionClaimGenerator { gen },
    )
}

pub struct PedersenContextInteractionClaimGenerator {
    pub gen: Option<PedersenInteractionClaimGenerator>,
}
pub struct PedersenInteractionClaimGenerator {
    pub pedersen_aggregator_interaction_gen:
        pedersen_aggregator_window_bits_18::InteractionClaimGenerator,
    pub partial_ec_mul_interaction_gen: partial_ec_mul_window_bits_18::InteractionClaimGenerator,
    pub pedersen_points_table_interaction_gen:
        pedersen_points_table_window_bits_18::InteractionClaimGenerator,
}
