use stwo_constraint_framework::{PreprocessedColumn, PreprocessedColumnIdx};
use stwo_verifier_core::Hash;

// IMPORTANT: This file must exactly match the output and ordering of the prover preprocessed
// trace declaration. If the function changes, this array must be updated to stay in sync.
// https://github.com/starkware-libs/stwo-cairo/blob/d8b2aff6ac7c4e991b9e91140ff20d6e0d9ea0b3/stwo_cairo_prover/crates/common/src/preprocessed_columns/preprocessed_trace.rs#L43

pub const NUM_PREPROCESSED_COLUMNS: u32 = 107;

pub const PREPROCESSED_COLUMNS: [PreprocessedColumn; NUM_PREPROCESSED_COLUMNS] = [
    PreprocessedColumn { log_size: 25 }, // PreprocessedColumn::Seq(25),
    PreprocessedColumn { log_size: 24 }, // PreprocessedColumn::Seq(24),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::Seq(23),
    PreprocessedColumn { log_size: 22 }, // PreprocessedColumn::Seq(22),
    PreprocessedColumn { log_size: 21 }, // PreprocessedColumn::Seq(21),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::Seq(20),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::BitwiseXor((10, 0)),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::BitwiseXor((10, 1)),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::BitwiseXor((10, 2)),
    PreprocessedColumn { log_size: 19 }, // PreprocessedColumn::Seq(19),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::Seq(18),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::BitwiseXor((9, 0)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::BitwiseXor((9, 1)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::BitwiseXor((9, 2)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck2(([9, 9], 0)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck2(([9, 9], 1)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 0)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 1)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 2)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 3)),
    PreprocessedColumn { log_size: 17 }, // PreprocessedColumn::Seq(17),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::Seq(16),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::BitwiseXor((8, 0)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::BitwiseXor((8, 1)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::BitwiseXor((8, 2)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 0)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 1)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 2)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 3)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::Seq(15),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 0)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 1)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 2)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 3)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 4)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::Seq(14),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::BitwiseXor((7, 0)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::BitwiseXor((7, 1)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::BitwiseXor((7, 2)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::RangeCheck3(([7, 2, 5], 0)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::RangeCheck3(([7, 2, 5], 1)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::RangeCheck3(([7, 2, 5], 2)),
    PreprocessedColumn { log_size: 13 }, // PreprocessedColumn::Seq(13),
    PreprocessedColumn { log_size: 12 }, // PreprocessedColumn::Seq(12),
    PreprocessedColumn { log_size: 11 }, // PreprocessedColumn::Seq(11),
    PreprocessedColumn { log_size: 10 }, // PreprocessedColumn::Seq(10),
    PreprocessedColumn { log_size: 9 }, // PreprocessedColumn::Seq(9),
    PreprocessedColumn { log_size: 9 }, // PreprocessedColumn::RangeCheck2(([5, 4], 0)),
    PreprocessedColumn { log_size: 9 }, // PreprocessedColumn::RangeCheck2(([5, 4], 1)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::Seq(8),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::BitwiseXor((4, 0)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::BitwiseXor((4, 1)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::BitwiseXor((4, 2)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::RangeCheck2(([4, 4], 0)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::RangeCheck2(([4, 4], 1)),
    PreprocessedColumn { log_size: 7 }, // PreprocessedColumn::Seq(7),
    PreprocessedColumn { log_size: 7 }, // PreprocessedColumn::RangeCheck2(([4, 3], 0)),
    PreprocessedColumn { log_size: 7 }, // PreprocessedColumn::RangeCheck2(([4, 3], 1)),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::Seq(6),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(0),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(1),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(2),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(3),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(4),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(5),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(6),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(7),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(8),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(9),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(10),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(11),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(12),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(13),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(14),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(15),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(16),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(17),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(18),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(19),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(20),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(21),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(22),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(23),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(24),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(25),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(26),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(27),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(28),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(29),
    PreprocessedColumn { log_size: 5 }, // PreprocessedColumn::Seq(5),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::Seq(4),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(0),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(1),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(2),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(3),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(4),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(5),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(6),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(7),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(8),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(9),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(10),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(11),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(12),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(13),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(14),
    PreprocessedColumn { log_size: 4 } // PreprocessedColumn::BlakeSigma(15)
];


pub const SEQ__25_0_IDX: u32 = 0; // PreprocessedColumn::Seq(25),
pub const SEQ__24_0_IDX: u32 = 1; // PreprocessedColumn::Seq(24),
pub const SEQ__23_0_IDX: u32 = 2; // PreprocessedColumn::Seq(23),
pub const SEQ__22_0_IDX: u32 = 3; // PreprocessedColumn::Seq(22),
pub const SEQ__21_0_IDX: u32 = 4; // PreprocessedColumn::Seq(21),
pub const SEQ__20_0_IDX: u32 = 5; // PreprocessedColumn::Seq(20),
pub const BITWISE_XOR__10_0_IDX: u32 = 6; // PreprocessedColumn::BitwiseXor((10, 0)),
pub const BITWISE_XOR__10_1_IDX: u32 = 7; // PreprocessedColumn::BitwiseXor((10, 1)),
pub const BITWISE_XOR__10_2_IDX: u32 = 8; // PreprocessedColumn::BitwiseXor((10, 2)),
pub const SEQ__19_0_IDX: u32 = 9; // PreprocessedColumn::Seq(19),
pub const SEQ__18_0_IDX: u32 = 10; // PreprocessedColumn::Seq(18),
pub const BITWISE_XOR__9_0_IDX: u32 = 11; // PreprocessedColumn::BitwiseXor((9, 0)),
pub const BITWISE_XOR__9_1_IDX: u32 = 12; // PreprocessedColumn::BitwiseXor((9, 1)),
pub const BITWISE_XOR__9_2_IDX: u32 = 13; // PreprocessedColumn::BitwiseXor((9, 2)),
pub const RANGE_CHECK_2_9_9_0_IDX: u32 = 14; // PreprocessedColumn::RangeCheck2(([9, 9], 0)),
pub const RANGE_CHECK_2_9_9_1_IDX: u32 = 15; // PreprocessedColumn::RangeCheck2(([9, 9], 1)),
pub const RANGE_CHECK_4_3_6_6_3_0_IDX: u32 =
    16; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 0)),
pub const RANGE_CHECK_4_3_6_6_3_1_IDX: u32 =
    17; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 1)),
pub const RANGE_CHECK_4_3_6_6_3_2_IDX: u32 =
    18; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 2)),
pub const RANGE_CHECK_4_3_6_6_3_3_IDX: u32 =
    19; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 3)),
pub const SEQ__17_0_IDX: u32 = 20; // PreprocessedColumn::Seq(17),
pub const SEQ__16_0_IDX: u32 = 21; // PreprocessedColumn::Seq(16),
pub const BITWISE_XOR__8_0_IDX: u32 = 22; // PreprocessedColumn::BitwiseXor((8, 0)),
pub const BITWISE_XOR__8_1_IDX: u32 = 23; // PreprocessedColumn::BitwiseXor((8, 1)),
pub const BITWISE_XOR__8_2_IDX: u32 = 24; // PreprocessedColumn::BitwiseXor((8, 2)),
pub const RANGE_CHECK_4_4_4_4_4_0_IDX: u32 =
    25; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 0)),
pub const RANGE_CHECK_4_4_4_4_4_1_IDX: u32 =
    26; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 1)),
pub const RANGE_CHECK_4_4_4_4_4_2_IDX: u32 =
    27; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 2)),
pub const RANGE_CHECK_4_4_4_4_4_3_IDX: u32 =
    28; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 3)),
pub const SEQ__15_0_IDX: u32 = 29; // PreprocessedColumn::Seq(15),
pub const RANGE_CHECK_5_3_3_3_3_3_0_IDX: u32 =
    30; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 0)),
pub const RANGE_CHECK_5_3_3_3_3_3_1_IDX: u32 =
    31; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 1)),
pub const RANGE_CHECK_5_3_3_3_3_3_2_IDX: u32 =
    32; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 2)),
pub const RANGE_CHECK_5_3_3_3_3_3_3_IDX: u32 =
    33; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 3)),
pub const RANGE_CHECK_5_3_3_3_3_3_4_IDX: u32 =
    34; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 4)),
pub const SEQ__14_0_IDX: u32 = 35; // PreprocessedColumn::Seq(14),
pub const BITWISE_XOR__7_0_IDX: u32 = 36; // PreprocessedColumn::BitwiseXor((7, 0)),
pub const BITWISE_XOR__7_1_IDX: u32 = 37; // PreprocessedColumn::BitwiseXor((7, 1)),
pub const BITWISE_XOR__7_2_IDX: u32 = 38; // PreprocessedColumn::BitwiseXor((7, 2)),
pub const RANGE_CHECK_3_7_2_5_0_IDX: u32 = 39; // PreprocessedColumn::RangeCheck3(([7, 2, 5], 0)),
pub const RANGE_CHECK_3_7_2_5_1_IDX: u32 = 40; // PreprocessedColumn::RangeCheck3(([7, 2, 5], 1)),
pub const RANGE_CHECK_3_7_2_5_2_IDX: u32 = 41; // PreprocessedColumn::RangeCheck3(([7, 2, 5], 2)),
pub const SEQ__13_0_IDX: u32 = 42; // PreprocessedColumn::Seq(13),
pub const SEQ__12_0_IDX: u32 = 43; // PreprocessedColumn::Seq(12),
pub const SEQ__11_0_IDX: u32 = 44; // PreprocessedColumn::Seq(11),
pub const SEQ__10_0_IDX: u32 = 45; // PreprocessedColumn::Seq(10),
pub const SEQ__9_0_IDX: u32 = 46; // PreprocessedColumn::Seq(9),
pub const RANGE_CHECK_2_5_4_0_IDX: u32 = 47; // PreprocessedColumn::RangeCheck2(([5, 4], 0)),
pub const RANGE_CHECK_2_5_4_1_IDX: u32 = 48; // PreprocessedColumn::RangeCheck2(([5, 4], 1)),
pub const SEQ__8_0_IDX: u32 = 49; // PreprocessedColumn::Seq(8),
pub const BITWISE_XOR__4_0_IDX: u32 = 50; // PreprocessedColumn::BitwiseXor((4, 0)),
pub const BITWISE_XOR__4_1_IDX: u32 = 51; // PreprocessedColumn::BitwiseXor((4, 1)),
pub const BITWISE_XOR__4_2_IDX: u32 = 52; // PreprocessedColumn::BitwiseXor((4, 2)),
pub const RANGE_CHECK_2_4_4_0_IDX: u32 = 53; // PreprocessedColumn::RangeCheck2(([4, 4], 0)),
pub const RANGE_CHECK_2_4_4_1_IDX: u32 = 54; // PreprocessedColumn::RangeCheck2(([4, 4], 1)),
pub const SEQ__7_0_IDX: u32 = 55; // PreprocessedColumn::Seq(7),
pub const RANGE_CHECK_2_4_3_0_IDX: u32 = 56; // PreprocessedColumn::RangeCheck2(([4, 3], 0)),
pub const RANGE_CHECK_2_4_3_1_IDX: u32 = 57; // PreprocessedColumn::RangeCheck2(([4, 3], 1)),
pub const SEQ__6_0_IDX: u32 = 58; // PreprocessedColumn::Seq(6),
pub const POSEIDON_ROUND_KEYS__0_IDX: u32 = 59; // PreprocessedColumn::PoseidonRoundKeys(0),
pub const POSEIDON_ROUND_KEYS__1_IDX: u32 = 60; // PreprocessedColumn::PoseidonRoundKeys(1),
pub const POSEIDON_ROUND_KEYS__2_IDX: u32 = 61; // PreprocessedColumn::PoseidonRoundKeys(2),
pub const POSEIDON_ROUND_KEYS__3_IDX: u32 = 62; // PreprocessedColumn::PoseidonRoundKeys(3),
pub const POSEIDON_ROUND_KEYS__4_IDX: u32 = 63; // PreprocessedColumn::PoseidonRoundKeys(4),
pub const POSEIDON_ROUND_KEYS__5_IDX: u32 = 64; // PreprocessedColumn::PoseidonRoundKeys(5),
pub const POSEIDON_ROUND_KEYS__6_IDX: u32 = 65; // PreprocessedColumn::PoseidonRoundKeys(6),
pub const POSEIDON_ROUND_KEYS__7_IDX: u32 = 66; // PreprocessedColumn::PoseidonRoundKeys(7),
pub const POSEIDON_ROUND_KEYS__8_IDX: u32 = 67; // PreprocessedColumn::PoseidonRoundKeys(8),
pub const POSEIDON_ROUND_KEYS__9_IDX: u32 = 68; // PreprocessedColumn::PoseidonRoundKeys(9),
pub const POSEIDON_ROUND_KEYS__10_IDX: u32 = 69; // PreprocessedColumn::PoseidonRoundKeys(10),
pub const POSEIDON_ROUND_KEYS__11_IDX: u32 = 70; // PreprocessedColumn::PoseidonRoundKeys(11),
pub const POSEIDON_ROUND_KEYS__12_IDX: u32 = 71; // PreprocessedColumn::PoseidonRoundKeys(12),
pub const POSEIDON_ROUND_KEYS__13_IDX: u32 = 72; // PreprocessedColumn::PoseidonRoundKeys(13),
pub const POSEIDON_ROUND_KEYS__14_IDX: u32 = 73; // PreprocessedColumn::PoseidonRoundKeys(14),
pub const POSEIDON_ROUND_KEYS__15_IDX: u32 = 74; // PreprocessedColumn::PoseidonRoundKeys(15),
pub const POSEIDON_ROUND_KEYS__16_IDX: u32 = 75; // PreprocessedColumn::PoseidonRoundKeys(16),
pub const POSEIDON_ROUND_KEYS__17_IDX: u32 = 76; // PreprocessedColumn::PoseidonRoundKeys(17),
pub const POSEIDON_ROUND_KEYS__18_IDX: u32 = 77; // PreprocessedColumn::PoseidonRoundKeys(18),
pub const POSEIDON_ROUND_KEYS__19_IDX: u32 = 78; // PreprocessedColumn::PoseidonRoundKeys(19),
pub const POSEIDON_ROUND_KEYS__20_IDX: u32 = 79; // PreprocessedColumn::PoseidonRoundKeys(20),
pub const POSEIDON_ROUND_KEYS__21_IDX: u32 = 80; // PreprocessedColumn::PoseidonRoundKeys(21),
pub const POSEIDON_ROUND_KEYS__22_IDX: u32 = 81; // PreprocessedColumn::PoseidonRoundKeys(22),
pub const POSEIDON_ROUND_KEYS__23_IDX: u32 = 82; // PreprocessedColumn::PoseidonRoundKeys(23),
pub const POSEIDON_ROUND_KEYS__24_IDX: u32 = 83; // PreprocessedColumn::PoseidonRoundKeys(24),
pub const POSEIDON_ROUND_KEYS__25_IDX: u32 = 84; // PreprocessedColumn::PoseidonRoundKeys(25),
pub const POSEIDON_ROUND_KEYS__26_IDX: u32 = 85; // PreprocessedColumn::PoseidonRoundKeys(26),
pub const POSEIDON_ROUND_KEYS__27_IDX: u32 = 86; // PreprocessedColumn::PoseidonRoundKeys(27),
pub const POSEIDON_ROUND_KEYS__28_IDX: u32 = 87; // PreprocessedColumn::PoseidonRoundKeys(28),
pub const POSEIDON_ROUND_KEYS__29_IDX: u32 = 88; // PreprocessedColumn::PoseidonRoundKeys(29),
pub const SEQ__5_0_IDX: u32 = 89; // PreprocessedColumn::Seq(5),
pub const SEQ__4_0_IDX: u32 = 90; // PreprocessedColumn::Seq(4),
pub const BLAKE_SIGMA__0_IDX: u32 = 91; // PreprocessedColumn::BlakeSigma(0),
pub const BLAKE_SIGMA__1_IDX: u32 = 92; // PreprocessedColumn::BlakeSigma(1),
pub const BLAKE_SIGMA__2_IDX: u32 = 93; // PreprocessedColumn::BlakeSigma(2),
pub const BLAKE_SIGMA__3_IDX: u32 = 94; // PreprocessedColumn::BlakeSigma(3),
pub const BLAKE_SIGMA__4_IDX: u32 = 95; // PreprocessedColumn::BlakeSigma(4),
pub const BLAKE_SIGMA__5_IDX: u32 = 96; // PreprocessedColumn::BlakeSigma(5),
pub const BLAKE_SIGMA__6_IDX: u32 = 97; // PreprocessedColumn::BlakeSigma(6),
pub const BLAKE_SIGMA__7_IDX: u32 = 98; // PreprocessedColumn::BlakeSigma(7),
pub const BLAKE_SIGMA__8_IDX: u32 = 99; // PreprocessedColumn::BlakeSigma(8),
pub const BLAKE_SIGMA__9_IDX: u32 = 100; // PreprocessedColumn::BlakeSigma(9),
pub const BLAKE_SIGMA__10_IDX: u32 = 101; // PreprocessedColumn::BlakeSigma(10),
pub const BLAKE_SIGMA__11_IDX: u32 = 102; // PreprocessedColumn::BlakeSigma(11),
pub const BLAKE_SIGMA__12_IDX: u32 = 103; // PreprocessedColumn::BlakeSigma(12),
pub const BLAKE_SIGMA__13_IDX: u32 = 104; // PreprocessedColumn::BlakeSigma(13),
pub const BLAKE_SIGMA__14_IDX: u32 = 105; // PreprocessedColumn::BlakeSigma(14),
pub const BLAKE_SIGMA__15_IDX: u32 = 106; // PreprocessedColumn::BlakeSigma(15)

pub fn seq_column_idx(log_size: u32) -> PreprocessedColumnIdx {
    match log_size {
        0 | 1 | 2 | 3 => panic!(),
        4 => SEQ__4_0_IDX,
        5 => SEQ__5_0_IDX,
        6 => SEQ__6_0_IDX,
        7 => SEQ__7_0_IDX,
        8 => SEQ__8_0_IDX,
        9 => SEQ__9_0_IDX,
        10 => SEQ__10_0_IDX,
        11 => SEQ__11_0_IDX,
        12 => SEQ__12_0_IDX,
        13 => SEQ__13_0_IDX,
        14 => SEQ__14_0_IDX,
        15 => SEQ__15_0_IDX,
        16 => SEQ__16_0_IDX,
        17 => SEQ__17_0_IDX,
        18 => SEQ__18_0_IDX,
        19 => SEQ__19_0_IDX,
        20 => SEQ__20_0_IDX,
        21 => SEQ__21_0_IDX,
        22 => SEQ__22_0_IDX,
        23 => SEQ__23_0_IDX,
        24 => SEQ__24_0_IDX,
        25 => SEQ__25_0_IDX,
        _ => panic!(),
    }
}

/// Returns PreProcessedTrace::canonical_without_pedersen root for the given blowup factor.
pub fn preprocessed_root(log_blowup_factor: u32) -> Hash {
    match log_blowup_factor - 1 {
        0 => 0x3ab732352bb777ef4a2297a6f4f41b362f2f3bda902645c5cf7a3f33803ad13,
        1 => 0x6a03b3005906fc43caea6272a5abb3678b07eefd595fd2afb5ddb980e682781,
        2 => 0x71944a190ebd4721f696f8d1c5e7a95e8efc70d104d7391b0de4ac965baba70,
        3 => 0x5d83b175ae26614b615d51c92927272a7b5b50a74afa6b84536142db0a25728,
        4 => 0x6ba5cf14072a327807b33acc97bb365a796f9bedfcabde9461a25131205ff83,
        _ => panic!("invalid blowup factor"),
    }
}
