use core::box::BoxImpl;
use stwo_constraint_framework::{PreprocessedColumn, PreprocessedColumnIdx};
use stwo_verifier_core::Hash;

// IMPORTANT: This file must exactly match the output and ordering of the prover preprocessed
// trace declaration. If the function changes, this array must be updated to stay in sync.
// https://github.com/starkware-libs/stwo-cairo/blob/d8b2aff6ac7c4e991b9e91140ff20d6e0d9ea0b3/stwo_cairo_prover/crates/common/src/preprocessed_columns/preprocessed_trace.rs#L43

pub const NUM_PREPROCESSED_COLUMNS: u32 = 163;

pub const PREPROCESSED_COLUMNS: [PreprocessedColumn; NUM_PREPROCESSED_COLUMNS] = [
    PreprocessedColumn { log_size: 25 }, // PreprocessedColumn::Seq(25),
    PreprocessedColumn { log_size: 24 }, // PreprocessedColumn::Seq(24),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::Seq(23),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(0),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(1),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(2),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(3),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(4),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(5),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(6),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(7),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(8),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(9),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(10),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(11),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(12),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(13),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(14),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(15),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(16),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(17),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(18),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(19),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(20),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(21),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(22),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(23),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(24),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(25),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(26),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(27),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(28),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(29),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(30),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(31),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(32),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(33),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(34),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(35),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(36),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(37),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(38),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(39),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(40),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(41),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(42),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(43),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(44),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(45),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(46),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(47),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(48),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(49),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(50),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(51),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(52),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(53),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(54),
    PreprocessedColumn { log_size: 23 }, // PreprocessedColumn::PedersenPoints(55),
    PreprocessedColumn { log_size: 22 }, // PreprocessedColumn::Seq(22),
    PreprocessedColumn { log_size: 21 }, // PreprocessedColumn::Seq(21),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::Seq(20),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::BitwiseXor((10, 0)),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::BitwiseXor((10, 1)),
    PreprocessedColumn { log_size: 20 }, // PreprocessedColumn::BitwiseXor((10, 2)),
    PreprocessedColumn { log_size: 19 }, // PreprocessedColumn::Seq(19),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::Seq(18),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::BitwiseXor((9, 0)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::BitwiseXor((9, 1)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::BitwiseXor((9, 2)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck2(([9, 9], 0)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck2(([9, 9], 1)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 0)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 1)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 2)),
    PreprocessedColumn { log_size: 18 }, // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 3)),
    PreprocessedColumn { log_size: 17 }, // PreprocessedColumn::Seq(17),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::Seq(16),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::BitwiseXor((8, 0)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::BitwiseXor((8, 1)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::BitwiseXor((8, 2)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 0)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 1)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 2)),
    PreprocessedColumn { log_size: 16 }, // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 3)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::Seq(15),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 0)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 1)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 2)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 3)),
    PreprocessedColumn { log_size: 15 }, // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 4)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::Seq(14),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::BitwiseXor((7, 0)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::BitwiseXor((7, 1)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::BitwiseXor((7, 2)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::RangeCheck3(([7, 2, 5], 0)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::RangeCheck3(([7, 2, 5], 1)),
    PreprocessedColumn { log_size: 14 }, // PreprocessedColumn::RangeCheck3(([7, 2, 5], 2)),
    PreprocessedColumn { log_size: 13 }, // PreprocessedColumn::Seq(13),
    PreprocessedColumn { log_size: 12 }, // PreprocessedColumn::Seq(12),
    PreprocessedColumn { log_size: 11 }, // PreprocessedColumn::Seq(11),
    PreprocessedColumn { log_size: 10 }, // PreprocessedColumn::Seq(10),
    PreprocessedColumn { log_size: 9 }, // PreprocessedColumn::Seq(9),
    PreprocessedColumn { log_size: 9 }, // PreprocessedColumn::RangeCheck2(([5, 4], 0)),
    PreprocessedColumn { log_size: 9 }, // PreprocessedColumn::RangeCheck2(([5, 4], 1)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::Seq(8),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::BitwiseXor((4, 0)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::BitwiseXor((4, 1)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::BitwiseXor((4, 2)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::RangeCheck2(([4, 4], 0)),
    PreprocessedColumn { log_size: 8 }, // PreprocessedColumn::RangeCheck2(([4, 4], 1)),
    PreprocessedColumn { log_size: 7 }, // PreprocessedColumn::Seq(7),
    PreprocessedColumn { log_size: 7 }, // PreprocessedColumn::RangeCheck2(([4, 3], 0)),
    PreprocessedColumn { log_size: 7 }, // PreprocessedColumn::RangeCheck2(([4, 3], 1)),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::Seq(6),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(0),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(1),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(2),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(3),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(4),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(5),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(6),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(7),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(8),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(9),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(10),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(11),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(12),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(13),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(14),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(15),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(16),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(17),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(18),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(19),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(20),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(21),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(22),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(23),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(24),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(25),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(26),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(27),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(28),
    PreprocessedColumn { log_size: 6 }, // PreprocessedColumn::PoseidonRoundKeys(29),
    PreprocessedColumn { log_size: 5 }, // PreprocessedColumn::Seq(5),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::Seq(4),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(0),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(1),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(2),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(3),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(4),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(5),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(6),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(7),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(8),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(9),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(10),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(11),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(12),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(13),
    PreprocessedColumn { log_size: 4 }, // PreprocessedColumn::BlakeSigma(14),
    PreprocessedColumn { log_size: 4 } // PreprocessedColumn::BlakeSigma(15)
];

pub const SEQ__25_0_IDX: u32 = 0; // PreprocessedColumn::Seq(25),
pub const SEQ__24_0_IDX: u32 = 1; // PreprocessedColumn::Seq(24),
pub const SEQ__23_0_IDX: u32 = 2; // PreprocessedColumn::Seq(23),
pub const PEDERSEN_POINTS__0_IDX: u32 = 3; // PreprocessedColumn::PedersenPoints(0),
pub const PEDERSEN_POINTS__1_IDX: u32 = 4; // PreprocessedColumn::PedersenPoints(1),
pub const PEDERSEN_POINTS__2_IDX: u32 = 5; // PreprocessedColumn::PedersenPoints(2),
pub const PEDERSEN_POINTS__3_IDX: u32 = 6; // PreprocessedColumn::PedersenPoints(3),
pub const PEDERSEN_POINTS__4_IDX: u32 = 7; // PreprocessedColumn::PedersenPoints(4),
pub const PEDERSEN_POINTS__5_IDX: u32 = 8; // PreprocessedColumn::PedersenPoints(5),
pub const PEDERSEN_POINTS__6_IDX: u32 = 9; // PreprocessedColumn::PedersenPoints(6),
pub const PEDERSEN_POINTS__7_IDX: u32 = 10; // PreprocessedColumn::PedersenPoints(7),
pub const PEDERSEN_POINTS__8_IDX: u32 = 11; // PreprocessedColumn::PedersenPoints(8),
pub const PEDERSEN_POINTS__9_IDX: u32 = 12; // PreprocessedColumn::PedersenPoints(9),
pub const PEDERSEN_POINTS__10_IDX: u32 = 13; // PreprocessedColumn::PedersenPoints(10),
pub const PEDERSEN_POINTS__11_IDX: u32 = 14; // PreprocessedColumn::PedersenPoints(11),
pub const PEDERSEN_POINTS__12_IDX: u32 = 15; // PreprocessedColumn::PedersenPoints(12),
pub const PEDERSEN_POINTS__13_IDX: u32 = 16; // PreprocessedColumn::PedersenPoints(13),
pub const PEDERSEN_POINTS__14_IDX: u32 = 17; // PreprocessedColumn::PedersenPoints(14),
pub const PEDERSEN_POINTS__15_IDX: u32 = 18; // PreprocessedColumn::PedersenPoints(15),
pub const PEDERSEN_POINTS__16_IDX: u32 = 19; // PreprocessedColumn::PedersenPoints(16),
pub const PEDERSEN_POINTS__17_IDX: u32 = 20; // PreprocessedColumn::PedersenPoints(17),
pub const PEDERSEN_POINTS__18_IDX: u32 = 21; // PreprocessedColumn::PedersenPoints(18),
pub const PEDERSEN_POINTS__19_IDX: u32 = 22; // PreprocessedColumn::PedersenPoints(19),
pub const PEDERSEN_POINTS__20_IDX: u32 = 23; // PreprocessedColumn::PedersenPoints(20),
pub const PEDERSEN_POINTS__21_IDX: u32 = 24; // PreprocessedColumn::PedersenPoints(21),
pub const PEDERSEN_POINTS__22_IDX: u32 = 25; // PreprocessedColumn::PedersenPoints(22),
pub const PEDERSEN_POINTS__23_IDX: u32 = 26; // PreprocessedColumn::PedersenPoints(23),
pub const PEDERSEN_POINTS__24_IDX: u32 = 27; // PreprocessedColumn::PedersenPoints(24),
pub const PEDERSEN_POINTS__25_IDX: u32 = 28; // PreprocessedColumn::PedersenPoints(25),
pub const PEDERSEN_POINTS__26_IDX: u32 = 29; // PreprocessedColumn::PedersenPoints(26),
pub const PEDERSEN_POINTS__27_IDX: u32 = 30; // PreprocessedColumn::PedersenPoints(27),
pub const PEDERSEN_POINTS__28_IDX: u32 = 31; // PreprocessedColumn::PedersenPoints(28),
pub const PEDERSEN_POINTS__29_IDX: u32 = 32; // PreprocessedColumn::PedersenPoints(29),
pub const PEDERSEN_POINTS__30_IDX: u32 = 33; // PreprocessedColumn::PedersenPoints(30),
pub const PEDERSEN_POINTS__31_IDX: u32 = 34; // PreprocessedColumn::PedersenPoints(31),
pub const PEDERSEN_POINTS__32_IDX: u32 = 35; // PreprocessedColumn::PedersenPoints(32),
pub const PEDERSEN_POINTS__33_IDX: u32 = 36; // PreprocessedColumn::PedersenPoints(33),
pub const PEDERSEN_POINTS__34_IDX: u32 = 37; // PreprocessedColumn::PedersenPoints(34),
pub const PEDERSEN_POINTS__35_IDX: u32 = 38; // PreprocessedColumn::PedersenPoints(35),
pub const PEDERSEN_POINTS__36_IDX: u32 = 39; // PreprocessedColumn::PedersenPoints(36),
pub const PEDERSEN_POINTS__37_IDX: u32 = 40; // PreprocessedColumn::PedersenPoints(37),
pub const PEDERSEN_POINTS__38_IDX: u32 = 41; // PreprocessedColumn::PedersenPoints(38),
pub const PEDERSEN_POINTS__39_IDX: u32 = 42; // PreprocessedColumn::PedersenPoints(39),
pub const PEDERSEN_POINTS__40_IDX: u32 = 43; // PreprocessedColumn::PedersenPoints(40),
pub const PEDERSEN_POINTS__41_IDX: u32 = 44; // PreprocessedColumn::PedersenPoints(41),
pub const PEDERSEN_POINTS__42_IDX: u32 = 45; // PreprocessedColumn::PedersenPoints(42),
pub const PEDERSEN_POINTS__43_IDX: u32 = 46; // PreprocessedColumn::PedersenPoints(43),
pub const PEDERSEN_POINTS__44_IDX: u32 = 47; // PreprocessedColumn::PedersenPoints(44),
pub const PEDERSEN_POINTS__45_IDX: u32 = 48; // PreprocessedColumn::PedersenPoints(45),
pub const PEDERSEN_POINTS__46_IDX: u32 = 49; // PreprocessedColumn::PedersenPoints(46),
pub const PEDERSEN_POINTS__47_IDX: u32 = 50; // PreprocessedColumn::PedersenPoints(47),
pub const PEDERSEN_POINTS__48_IDX: u32 = 51; // PreprocessedColumn::PedersenPoints(48),
pub const PEDERSEN_POINTS__49_IDX: u32 = 52; // PreprocessedColumn::PedersenPoints(49),
pub const PEDERSEN_POINTS__50_IDX: u32 = 53; // PreprocessedColumn::PedersenPoints(50),
pub const PEDERSEN_POINTS__51_IDX: u32 = 54; // PreprocessedColumn::PedersenPoints(51),
pub const PEDERSEN_POINTS__52_IDX: u32 = 55; // PreprocessedColumn::PedersenPoints(52),
pub const PEDERSEN_POINTS__53_IDX: u32 = 56; // PreprocessedColumn::PedersenPoints(53),
pub const PEDERSEN_POINTS__54_IDX: u32 = 57; // PreprocessedColumn::PedersenPoints(54),
pub const PEDERSEN_POINTS__55_IDX: u32 = 58; // PreprocessedColumn::PedersenPoints(55),
pub const SEQ__22_0_IDX: u32 = 59; // PreprocessedColumn::Seq(22),
pub const SEQ__21_0_IDX: u32 = 60; // PreprocessedColumn::Seq(21),
pub const SEQ__20_0_IDX: u32 = 61; // PreprocessedColumn::Seq(20),
pub const BITWISE_XOR__10_0_IDX: u32 = 62; // PreprocessedColumn::BitwiseXor((10, 0)),
pub const BITWISE_XOR__10_1_IDX: u32 = 63; // PreprocessedColumn::BitwiseXor((10, 1)),
pub const BITWISE_XOR__10_2_IDX: u32 = 64; // PreprocessedColumn::BitwiseXor((10, 2)),
pub const SEQ__19_0_IDX: u32 = 65; // PreprocessedColumn::Seq(19),
pub const SEQ__18_0_IDX: u32 = 66; // PreprocessedColumn::Seq(18),
pub const BITWISE_XOR__9_0_IDX: u32 = 67; // PreprocessedColumn::BitwiseXor((9, 0)),
pub const BITWISE_XOR__9_1_IDX: u32 = 68; // PreprocessedColumn::BitwiseXor((9, 1)),
pub const BITWISE_XOR__9_2_IDX: u32 = 69; // PreprocessedColumn::BitwiseXor((9, 2)),
pub const RANGE_CHECK_2_9_9_0_IDX: u32 = 70; // PreprocessedColumn::RangeCheck2(([9, 9], 0)),
pub const RANGE_CHECK_2_9_9_1_IDX: u32 = 71; // PreprocessedColumn::RangeCheck2(([9, 9], 1)),
pub const RANGE_CHECK_4_3_6_6_3_0_IDX: u32 =
    72; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 0)),
pub const RANGE_CHECK_4_3_6_6_3_1_IDX: u32 =
    73; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 1)),
pub const RANGE_CHECK_4_3_6_6_3_2_IDX: u32 =
    74; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 2)),
pub const RANGE_CHECK_4_3_6_6_3_3_IDX: u32 =
    75; // PreprocessedColumn::RangeCheck4(([3, 6, 6, 3], 3)),
pub const SEQ__17_0_IDX: u32 = 76; // PreprocessedColumn::Seq(17),
pub const SEQ__16_0_IDX: u32 = 77; // PreprocessedColumn::Seq(16),
pub const BITWISE_XOR__8_0_IDX: u32 = 78; // PreprocessedColumn::BitwiseXor((8, 0)),
pub const BITWISE_XOR__8_1_IDX: u32 = 79; // PreprocessedColumn::BitwiseXor((8, 1)),
pub const BITWISE_XOR__8_2_IDX: u32 = 80; // PreprocessedColumn::BitwiseXor((8, 2)),
pub const RANGE_CHECK_4_4_4_4_4_0_IDX: u32 =
    81; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 0)),
pub const RANGE_CHECK_4_4_4_4_4_1_IDX: u32 =
    82; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 1)),
pub const RANGE_CHECK_4_4_4_4_4_2_IDX: u32 =
    83; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 2)),
pub const RANGE_CHECK_4_4_4_4_4_3_IDX: u32 =
    84; // PreprocessedColumn::RangeCheck4(([4, 4, 4, 4], 3)),
pub const SEQ__15_0_IDX: u32 = 85; // PreprocessedColumn::Seq(15),
pub const RANGE_CHECK_5_3_3_3_3_3_0_IDX: u32 =
    86; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 0)),
pub const RANGE_CHECK_5_3_3_3_3_3_1_IDX: u32 =
    87; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 1)),
pub const RANGE_CHECK_5_3_3_3_3_3_2_IDX: u32 =
    88; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 2)),
pub const RANGE_CHECK_5_3_3_3_3_3_3_IDX: u32 =
    89; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 3)),
pub const RANGE_CHECK_5_3_3_3_3_3_4_IDX: u32 =
    90; // PreprocessedColumn::RangeCheck5(([3, 3, 3, 3, 3], 4)),
pub const SEQ__14_0_IDX: u32 = 91; // PreprocessedColumn::Seq(14),
pub const BITWISE_XOR__7_0_IDX: u32 = 92; // PreprocessedColumn::BitwiseXor((7, 0)),
pub const BITWISE_XOR__7_1_IDX: u32 = 93; // PreprocessedColumn::BitwiseXor((7, 1)),
pub const BITWISE_XOR__7_2_IDX: u32 = 94; // PreprocessedColumn::BitwiseXor((7, 2)),
pub const RANGE_CHECK_3_7_2_5_0_IDX: u32 = 95; // PreprocessedColumn::RangeCheck3(([7, 2, 5], 0)),
pub const RANGE_CHECK_3_7_2_5_1_IDX: u32 = 96; // PreprocessedColumn::RangeCheck3(([7, 2, 5], 1)),
pub const RANGE_CHECK_3_7_2_5_2_IDX: u32 = 97; // PreprocessedColumn::RangeCheck3(([7, 2, 5], 2)),
pub const SEQ__13_0_IDX: u32 = 98; // PreprocessedColumn::Seq(13),
pub const SEQ__12_0_IDX: u32 = 99; // PreprocessedColumn::Seq(12),
pub const SEQ__11_0_IDX: u32 = 100; // PreprocessedColumn::Seq(11),
pub const SEQ__10_0_IDX: u32 = 101; // PreprocessedColumn::Seq(10),
pub const SEQ__9_0_IDX: u32 = 102; // PreprocessedColumn::Seq(9),
pub const RANGE_CHECK_2_5_4_0_IDX: u32 = 103; // PreprocessedColumn::RangeCheck2(([5, 4], 0)),
pub const RANGE_CHECK_2_5_4_1_IDX: u32 = 104; // PreprocessedColumn::RangeCheck2(([5, 4], 1)),
pub const SEQ__8_0_IDX: u32 = 105; // PreprocessedColumn::Seq(8),
pub const BITWISE_XOR__4_0_IDX: u32 = 106; // PreprocessedColumn::BitwiseXor((4, 0)),
pub const BITWISE_XOR__4_1_IDX: u32 = 107; // PreprocessedColumn::BitwiseXor((4, 1)),
pub const BITWISE_XOR__4_2_IDX: u32 = 108; // PreprocessedColumn::BitwiseXor((4, 2)),
pub const RANGE_CHECK_2_4_4_0_IDX: u32 = 109; // PreprocessedColumn::RangeCheck2(([4, 4], 0)),
pub const RANGE_CHECK_2_4_4_1_IDX: u32 = 110; // PreprocessedColumn::RangeCheck2(([4, 4], 1)),
pub const SEQ__7_0_IDX: u32 = 111; // PreprocessedColumn::Seq(7),
pub const RANGE_CHECK_2_4_3_0_IDX: u32 = 112; // PreprocessedColumn::RangeCheck2(([4, 3], 0)),
pub const RANGE_CHECK_2_4_3_1_IDX: u32 = 113; // PreprocessedColumn::RangeCheck2(([4, 3], 1)),
pub const SEQ__6_0_IDX: u32 = 114; // PreprocessedColumn::Seq(6),
pub const POSEIDON_ROUND_KEYS__0_IDX: u32 = 115; // PreprocessedColumn::PoseidonRoundKeys(0),
pub const POSEIDON_ROUND_KEYS__1_IDX: u32 = 116; // PreprocessedColumn::PoseidonRoundKeys(1),
pub const POSEIDON_ROUND_KEYS__2_IDX: u32 = 117; // PreprocessedColumn::PoseidonRoundKeys(2),
pub const POSEIDON_ROUND_KEYS__3_IDX: u32 = 118; // PreprocessedColumn::PoseidonRoundKeys(3),
pub const POSEIDON_ROUND_KEYS__4_IDX: u32 = 119; // PreprocessedColumn::PoseidonRoundKeys(4),
pub const POSEIDON_ROUND_KEYS__5_IDX: u32 = 120; // PreprocessedColumn::PoseidonRoundKeys(5),
pub const POSEIDON_ROUND_KEYS__6_IDX: u32 = 121; // PreprocessedColumn::PoseidonRoundKeys(6),
pub const POSEIDON_ROUND_KEYS__7_IDX: u32 = 122; // PreprocessedColumn::PoseidonRoundKeys(7),
pub const POSEIDON_ROUND_KEYS__8_IDX: u32 = 123; // PreprocessedColumn::PoseidonRoundKeys(8),
pub const POSEIDON_ROUND_KEYS__9_IDX: u32 = 124; // PreprocessedColumn::PoseidonRoundKeys(9),
pub const POSEIDON_ROUND_KEYS__10_IDX: u32 = 125; // PreprocessedColumn::PoseidonRoundKeys(10),
pub const POSEIDON_ROUND_KEYS__11_IDX: u32 = 126; // PreprocessedColumn::PoseidonRoundKeys(11),
pub const POSEIDON_ROUND_KEYS__12_IDX: u32 = 127; // PreprocessedColumn::PoseidonRoundKeys(12),
pub const POSEIDON_ROUND_KEYS__13_IDX: u32 = 128; // PreprocessedColumn::PoseidonRoundKeys(13),
pub const POSEIDON_ROUND_KEYS__14_IDX: u32 = 129; // PreprocessedColumn::PoseidonRoundKeys(14),
pub const POSEIDON_ROUND_KEYS__15_IDX: u32 = 130; // PreprocessedColumn::PoseidonRoundKeys(15),
pub const POSEIDON_ROUND_KEYS__16_IDX: u32 = 131; // PreprocessedColumn::PoseidonRoundKeys(16),
pub const POSEIDON_ROUND_KEYS__17_IDX: u32 = 132; // PreprocessedColumn::PoseidonRoundKeys(17),
pub const POSEIDON_ROUND_KEYS__18_IDX: u32 = 133; // PreprocessedColumn::PoseidonRoundKeys(18),
pub const POSEIDON_ROUND_KEYS__19_IDX: u32 = 134; // PreprocessedColumn::PoseidonRoundKeys(19),
pub const POSEIDON_ROUND_KEYS__20_IDX: u32 = 135; // PreprocessedColumn::PoseidonRoundKeys(20),
pub const POSEIDON_ROUND_KEYS__21_IDX: u32 = 136; // PreprocessedColumn::PoseidonRoundKeys(21),
pub const POSEIDON_ROUND_KEYS__22_IDX: u32 = 137; // PreprocessedColumn::PoseidonRoundKeys(22),
pub const POSEIDON_ROUND_KEYS__23_IDX: u32 = 138; // PreprocessedColumn::PoseidonRoundKeys(23),
pub const POSEIDON_ROUND_KEYS__24_IDX: u32 = 139; // PreprocessedColumn::PoseidonRoundKeys(24),
pub const POSEIDON_ROUND_KEYS__25_IDX: u32 = 140; // PreprocessedColumn::PoseidonRoundKeys(25),
pub const POSEIDON_ROUND_KEYS__26_IDX: u32 = 141; // PreprocessedColumn::PoseidonRoundKeys(26),
pub const POSEIDON_ROUND_KEYS__27_IDX: u32 = 142; // PreprocessedColumn::PoseidonRoundKeys(27),
pub const POSEIDON_ROUND_KEYS__28_IDX: u32 = 143; // PreprocessedColumn::PoseidonRoundKeys(28),
pub const POSEIDON_ROUND_KEYS__29_IDX: u32 = 144; // PreprocessedColumn::PoseidonRoundKeys(29),
pub const SEQ__5_0_IDX: u32 = 145; // PreprocessedColumn::Seq(5),
pub const SEQ__4_0_IDX: u32 = 146; // PreprocessedColumn::Seq(4),
pub const BLAKE_SIGMA__0_IDX: u32 = 147; // PreprocessedColumn::BlakeSigma(0),
pub const BLAKE_SIGMA__1_IDX: u32 = 148; // PreprocessedColumn::BlakeSigma(1),
pub const BLAKE_SIGMA__2_IDX: u32 = 149; // PreprocessedColumn::BlakeSigma(2),
pub const BLAKE_SIGMA__3_IDX: u32 = 150; // PreprocessedColumn::BlakeSigma(3),
pub const BLAKE_SIGMA__4_IDX: u32 = 151; // PreprocessedColumn::BlakeSigma(4),
pub const BLAKE_SIGMA__5_IDX: u32 = 152; // PreprocessedColumn::BlakeSigma(5),
pub const BLAKE_SIGMA__6_IDX: u32 = 153; // PreprocessedColumn::BlakeSigma(6),
pub const BLAKE_SIGMA__7_IDX: u32 = 154; // PreprocessedColumn::BlakeSigma(7),
pub const BLAKE_SIGMA__8_IDX: u32 = 155; // PreprocessedColumn::BlakeSigma(8),
pub const BLAKE_SIGMA__9_IDX: u32 = 156; // PreprocessedColumn::BlakeSigma(9),
pub const BLAKE_SIGMA__10_IDX: u32 = 157; // PreprocessedColumn::BlakeSigma(10),
pub const BLAKE_SIGMA__11_IDX: u32 = 158; // PreprocessedColumn::BlakeSigma(11),
pub const BLAKE_SIGMA__12_IDX: u32 = 159; // PreprocessedColumn::BlakeSigma(12),
pub const BLAKE_SIGMA__13_IDX: u32 = 160; // PreprocessedColumn::BlakeSigma(13),
pub const BLAKE_SIGMA__14_IDX: u32 = 161; // PreprocessedColumn::BlakeSigma(14),
pub const BLAKE_SIGMA__15_IDX: u32 = 162; // PreprocessedColumn::BlakeSigma(15)

pub fn seq_column_idx(log_size: u32) -> PreprocessedColumnIdx {
    match log_size {
        0 | 1 | 2 | 3 => panic!(),
        4 => SEQ__4_0_IDX,
        5 => SEQ__5_0_IDX,
        6 => SEQ__6_0_IDX,
        7 => SEQ__7_0_IDX,
        8 => SEQ__8_0_IDX,
        9 => SEQ__9_0_IDX,
        10 => SEQ__10_0_IDX,
        11 => SEQ__11_0_IDX,
        12 => SEQ__12_0_IDX,
        13 => SEQ__13_0_IDX,
        14 => SEQ__14_0_IDX,
        15 => SEQ__15_0_IDX,
        16 => SEQ__16_0_IDX,
        17 => SEQ__17_0_IDX,
        18 => SEQ__18_0_IDX,
        19 => SEQ__19_0_IDX,
        20 => SEQ__20_0_IDX,
        21 => SEQ__21_0_IDX,
        22 => SEQ__22_0_IDX,
        23 => SEQ__23_0_IDX,
        24 => SEQ__24_0_IDX,
        25 => SEQ__25_0_IDX,
        _ => panic!(),
    }
}

/// Returns PreProcessedTrace::canonical root for the given blowup factor.
pub fn preprocessed_root(log_blowup_factor: u32) -> Hash {
    match log_blowup_factor - 1 {
        0 => Hash {
            hash: BoxImpl::new(
                [
                    0xf9732e16, 0xc1939fd2, 0x9600624b, 0x54027597, 0x147cf8eb, 0xa6e086e0,
                    0x213f3f6c, 0x80ed895c,
                ],
            ),
        },
        1 => Hash {
            hash: BoxImpl::new(
                [
                    0x49552fad, 0xf58fc1b8, 0xb91475d6, 0x253d8dc2, 0x8d45ea26, 0x6171432b,
                    0xfa2e2acd, 0xd29221e0,
                ],
            ),
        },
        2 => Hash {
            hash: BoxImpl::new(
                [
                    0xf937429a, 0x97988c3c, 0x8bc41d5d, 0xeed48adf, 0x0faaade2, 0x49c43f67,
                    0x76ace5e2, 0xbbd1592b,
                ],
            ),
        },
        3 => Hash {
            hash: BoxImpl::new(
                [
                    0xe8de9fb1, 0x1496075a, 0x409c7ae5, 0x92531e0d, 0xd6442f98, 0x65210522,
                    0x8d9b085d, 0xa296d316,
                ],
            ),
        },
        4 => Hash {
            hash: BoxImpl::new(
                [
                    0xdfd138d0, 0x6f7446ef, 0x25c15cb8, 0x098dcd06, 0x2f478905, 0xca8fe8ff,
                    0x73484cd8, 0x8a711ab7,
                ],
            ),
        },
        _ => panic!("invalid blowup factor"),
    }
}
