use crate::components::prelude::constraint_eval::*;
use crate::components::range_check_mem_value_n_28::component::RangeCheckMemValueN28;
use crate::components::verify_mul_252::component::VerifyMul252;

#[derive(Copy, Clone, Serialize, Deserialize, CairoSerialize)]
pub struct Div252 {}

impl Div252 {
    #[allow(unused_parens)]
    #[allow(clippy::double_parens)]
    #[allow(non_snake_case)]
    #[allow(clippy::unused_unit)]
    #[allow(unused_variables)]
    pub fn evaluate<E: EvalAtRow>(
        [div_252_input_limb_0, div_252_input_limb_1, div_252_input_limb_2, div_252_input_limb_3, div_252_input_limb_4, div_252_input_limb_5, div_252_input_limb_6, div_252_input_limb_7, div_252_input_limb_8, div_252_input_limb_9, div_252_input_limb_10, div_252_input_limb_11, div_252_input_limb_12, div_252_input_limb_13, div_252_input_limb_14, div_252_input_limb_15, div_252_input_limb_16, div_252_input_limb_17, div_252_input_limb_18, div_252_input_limb_19, div_252_input_limb_20, div_252_input_limb_21, div_252_input_limb_22, div_252_input_limb_23, div_252_input_limb_24, div_252_input_limb_25, div_252_input_limb_26, div_252_input_limb_27, div_252_input_limb_28, div_252_input_limb_29, div_252_input_limb_30, div_252_input_limb_31, div_252_input_limb_32, div_252_input_limb_33, div_252_input_limb_34, div_252_input_limb_35, div_252_input_limb_36, div_252_input_limb_37, div_252_input_limb_38, div_252_input_limb_39, div_252_input_limb_40, div_252_input_limb_41, div_252_input_limb_42, div_252_input_limb_43, div_252_input_limb_44, div_252_input_limb_45, div_252_input_limb_46, div_252_input_limb_47, div_252_input_limb_48, div_252_input_limb_49, div_252_input_limb_50, div_252_input_limb_51, div_252_input_limb_52, div_252_input_limb_53, div_252_input_limb_54, div_252_input_limb_55]: [E::F; 56],
        div_res_limb_0_col0: E::F,
        div_res_limb_1_col1: E::F,
        div_res_limb_2_col2: E::F,
        div_res_limb_3_col3: E::F,
        div_res_limb_4_col4: E::F,
        div_res_limb_5_col5: E::F,
        div_res_limb_6_col6: E::F,
        div_res_limb_7_col7: E::F,
        div_res_limb_8_col8: E::F,
        div_res_limb_9_col9: E::F,
        div_res_limb_10_col10: E::F,
        div_res_limb_11_col11: E::F,
        div_res_limb_12_col12: E::F,
        div_res_limb_13_col13: E::F,
        div_res_limb_14_col14: E::F,
        div_res_limb_15_col15: E::F,
        div_res_limb_16_col16: E::F,
        div_res_limb_17_col17: E::F,
        div_res_limb_18_col18: E::F,
        div_res_limb_19_col19: E::F,
        div_res_limb_20_col20: E::F,
        div_res_limb_21_col21: E::F,
        div_res_limb_22_col22: E::F,
        div_res_limb_23_col23: E::F,
        div_res_limb_24_col24: E::F,
        div_res_limb_25_col25: E::F,
        div_res_limb_26_col26: E::F,
        div_res_limb_27_col27: E::F,
        k_col28: E::F,
        carry_0_col29: E::F,
        carry_1_col30: E::F,
        carry_2_col31: E::F,
        carry_3_col32: E::F,
        carry_4_col33: E::F,
        carry_5_col34: E::F,
        carry_6_col35: E::F,
        carry_7_col36: E::F,
        carry_8_col37: E::F,
        carry_9_col38: E::F,
        carry_10_col39: E::F,
        carry_11_col40: E::F,
        carry_12_col41: E::F,
        carry_13_col42: E::F,
        carry_14_col43: E::F,
        carry_15_col44: E::F,
        carry_16_col45: E::F,
        carry_17_col46: E::F,
        carry_18_col47: E::F,
        carry_19_col48: E::F,
        carry_20_col49: E::F,
        carry_21_col50: E::F,
        carry_22_col51: E::F,
        carry_23_col52: E::F,
        carry_24_col53: E::F,
        carry_25_col54: E::F,
        carry_26_col55: E::F,
        eval: &mut E,
        range_check_19_lookup_elements: &relations::RangeCheck_19,
        range_check_9_9_lookup_elements: &relations::RangeCheck_9_9,
    ) -> [E::F; 28] {
        let () = RangeCheckMemValueN28::evaluate(
            [
                div_res_limb_0_col0.clone(),
                div_res_limb_1_col1.clone(),
                div_res_limb_2_col2.clone(),
                div_res_limb_3_col3.clone(),
                div_res_limb_4_col4.clone(),
                div_res_limb_5_col5.clone(),
                div_res_limb_6_col6.clone(),
                div_res_limb_7_col7.clone(),
                div_res_limb_8_col8.clone(),
                div_res_limb_9_col9.clone(),
                div_res_limb_10_col10.clone(),
                div_res_limb_11_col11.clone(),
                div_res_limb_12_col12.clone(),
                div_res_limb_13_col13.clone(),
                div_res_limb_14_col14.clone(),
                div_res_limb_15_col15.clone(),
                div_res_limb_16_col16.clone(),
                div_res_limb_17_col17.clone(),
                div_res_limb_18_col18.clone(),
                div_res_limb_19_col19.clone(),
                div_res_limb_20_col20.clone(),
                div_res_limb_21_col21.clone(),
                div_res_limb_22_col22.clone(),
                div_res_limb_23_col23.clone(),
                div_res_limb_24_col24.clone(),
                div_res_limb_25_col25.clone(),
                div_res_limb_26_col26.clone(),
                div_res_limb_27_col27.clone(),
            ],
            eval,
            range_check_9_9_lookup_elements,
        );
        let () = VerifyMul252::evaluate(
            [
                div_252_input_limb_28.clone(),
                div_252_input_limb_29.clone(),
                div_252_input_limb_30.clone(),
                div_252_input_limb_31.clone(),
                div_252_input_limb_32.clone(),
                div_252_input_limb_33.clone(),
                div_252_input_limb_34.clone(),
                div_252_input_limb_35.clone(),
                div_252_input_limb_36.clone(),
                div_252_input_limb_37.clone(),
                div_252_input_limb_38.clone(),
                div_252_input_limb_39.clone(),
                div_252_input_limb_40.clone(),
                div_252_input_limb_41.clone(),
                div_252_input_limb_42.clone(),
                div_252_input_limb_43.clone(),
                div_252_input_limb_44.clone(),
                div_252_input_limb_45.clone(),
                div_252_input_limb_46.clone(),
                div_252_input_limb_47.clone(),
                div_252_input_limb_48.clone(),
                div_252_input_limb_49.clone(),
                div_252_input_limb_50.clone(),
                div_252_input_limb_51.clone(),
                div_252_input_limb_52.clone(),
                div_252_input_limb_53.clone(),
                div_252_input_limb_54.clone(),
                div_252_input_limb_55.clone(),
                div_res_limb_0_col0.clone(),
                div_res_limb_1_col1.clone(),
                div_res_limb_2_col2.clone(),
                div_res_limb_3_col3.clone(),
                div_res_limb_4_col4.clone(),
                div_res_limb_5_col5.clone(),
                div_res_limb_6_col6.clone(),
                div_res_limb_7_col7.clone(),
                div_res_limb_8_col8.clone(),
                div_res_limb_9_col9.clone(),
                div_res_limb_10_col10.clone(),
                div_res_limb_11_col11.clone(),
                div_res_limb_12_col12.clone(),
                div_res_limb_13_col13.clone(),
                div_res_limb_14_col14.clone(),
                div_res_limb_15_col15.clone(),
                div_res_limb_16_col16.clone(),
                div_res_limb_17_col17.clone(),
                div_res_limb_18_col18.clone(),
                div_res_limb_19_col19.clone(),
                div_res_limb_20_col20.clone(),
                div_res_limb_21_col21.clone(),
                div_res_limb_22_col22.clone(),
                div_res_limb_23_col23.clone(),
                div_res_limb_24_col24.clone(),
                div_res_limb_25_col25.clone(),
                div_res_limb_26_col26.clone(),
                div_res_limb_27_col27.clone(),
                div_252_input_limb_0.clone(),
                div_252_input_limb_1.clone(),
                div_252_input_limb_2.clone(),
                div_252_input_limb_3.clone(),
                div_252_input_limb_4.clone(),
                div_252_input_limb_5.clone(),
                div_252_input_limb_6.clone(),
                div_252_input_limb_7.clone(),
                div_252_input_limb_8.clone(),
                div_252_input_limb_9.clone(),
                div_252_input_limb_10.clone(),
                div_252_input_limb_11.clone(),
                div_252_input_limb_12.clone(),
                div_252_input_limb_13.clone(),
                div_252_input_limb_14.clone(),
                div_252_input_limb_15.clone(),
                div_252_input_limb_16.clone(),
                div_252_input_limb_17.clone(),
                div_252_input_limb_18.clone(),
                div_252_input_limb_19.clone(),
                div_252_input_limb_20.clone(),
                div_252_input_limb_21.clone(),
                div_252_input_limb_22.clone(),
                div_252_input_limb_23.clone(),
                div_252_input_limb_24.clone(),
                div_252_input_limb_25.clone(),
                div_252_input_limb_26.clone(),
                div_252_input_limb_27.clone(),
            ],
            k_col28.clone(),
            carry_0_col29.clone(),
            carry_1_col30.clone(),
            carry_2_col31.clone(),
            carry_3_col32.clone(),
            carry_4_col33.clone(),
            carry_5_col34.clone(),
            carry_6_col35.clone(),
            carry_7_col36.clone(),
            carry_8_col37.clone(),
            carry_9_col38.clone(),
            carry_10_col39.clone(),
            carry_11_col40.clone(),
            carry_12_col41.clone(),
            carry_13_col42.clone(),
            carry_14_col43.clone(),
            carry_15_col44.clone(),
            carry_16_col45.clone(),
            carry_17_col46.clone(),
            carry_18_col47.clone(),
            carry_19_col48.clone(),
            carry_20_col49.clone(),
            carry_21_col50.clone(),
            carry_22_col51.clone(),
            carry_23_col52.clone(),
            carry_24_col53.clone(),
            carry_25_col54.clone(),
            carry_26_col55.clone(),
            eval,
            range_check_19_lookup_elements,
        );
        [
            div_res_limb_0_col0.clone(),
            div_res_limb_1_col1.clone(),
            div_res_limb_2_col2.clone(),
            div_res_limb_3_col3.clone(),
            div_res_limb_4_col4.clone(),
            div_res_limb_5_col5.clone(),
            div_res_limb_6_col6.clone(),
            div_res_limb_7_col7.clone(),
            div_res_limb_8_col8.clone(),
            div_res_limb_9_col9.clone(),
            div_res_limb_10_col10.clone(),
            div_res_limb_11_col11.clone(),
            div_res_limb_12_col12.clone(),
            div_res_limb_13_col13.clone(),
            div_res_limb_14_col14.clone(),
            div_res_limb_15_col15.clone(),
            div_res_limb_16_col16.clone(),
            div_res_limb_17_col17.clone(),
            div_res_limb_18_col18.clone(),
            div_res_limb_19_col19.clone(),
            div_res_limb_20_col20.clone(),
            div_res_limb_21_col21.clone(),
            div_res_limb_22_col22.clone(),
            div_res_limb_23_col23.clone(),
            div_res_limb_24_col24.clone(),
            div_res_limb_25_col25.clone(),
            div_res_limb_26_col26.clone(),
            div_res_limb_27_col27.clone(),
        ]
    }
}
