// This file was created by the AIR team.

use crate::components::subroutines::bitwise_xor_num_bits_8::bitwise_xor_num_bits_8_evaluate;
use crate::components::subroutines::read_u_32::read_u_32_evaluate;
use crate::components::subroutines::split_16_low_part_size_8::split_16_low_part_size_8_evaluate;
use crate::prelude::*;


pub fn create_blake_round_input_evaluate(
    input: [QM31; 4],
    low_16_bits_col0: QM31,
    high_16_bits_col1: QM31,
    low_7_ms_bits_col2: QM31,
    high_14_ms_bits_col3: QM31,
    high_5_ms_bits_col4: QM31,
    state_0_id_col5: QM31,
    low_16_bits_col6: QM31,
    high_16_bits_col7: QM31,
    low_7_ms_bits_col8: QM31,
    high_14_ms_bits_col9: QM31,
    high_5_ms_bits_col10: QM31,
    state_1_id_col11: QM31,
    low_16_bits_col12: QM31,
    high_16_bits_col13: QM31,
    low_7_ms_bits_col14: QM31,
    high_14_ms_bits_col15: QM31,
    high_5_ms_bits_col16: QM31,
    state_2_id_col17: QM31,
    low_16_bits_col18: QM31,
    high_16_bits_col19: QM31,
    low_7_ms_bits_col20: QM31,
    high_14_ms_bits_col21: QM31,
    high_5_ms_bits_col22: QM31,
    state_3_id_col23: QM31,
    low_16_bits_col24: QM31,
    high_16_bits_col25: QM31,
    low_7_ms_bits_col26: QM31,
    high_14_ms_bits_col27: QM31,
    high_5_ms_bits_col28: QM31,
    state_4_id_col29: QM31,
    low_16_bits_col30: QM31,
    high_16_bits_col31: QM31,
    low_7_ms_bits_col32: QM31,
    high_14_ms_bits_col33: QM31,
    high_5_ms_bits_col34: QM31,
    state_5_id_col35: QM31,
    low_16_bits_col36: QM31,
    high_16_bits_col37: QM31,
    low_7_ms_bits_col38: QM31,
    high_14_ms_bits_col39: QM31,
    high_5_ms_bits_col40: QM31,
    state_6_id_col41: QM31,
    low_16_bits_col42: QM31,
    high_16_bits_col43: QM31,
    low_7_ms_bits_col44: QM31,
    high_14_ms_bits_col45: QM31,
    high_5_ms_bits_col46: QM31,
    state_7_id_col47: QM31,
    ms_8_bits_col48: QM31,
    ms_8_bits_col49: QM31,
    xor_col50: QM31,
    xor_col51: QM31,
    xor_col52: QM31,
    xor_col53: QM31,
    common_lookup_elements: @CommonLookupElements,
    ref range_check_7_2_5_sum_0: QM31,
    ref numerator_0: QM31,
    ref memory_address_to_id_sum_1: QM31,
    ref numerator_1: QM31,
    ref memory_id_to_big_sum_2: QM31,
    ref numerator_2: QM31,
    ref range_check_7_2_5_sum_3: QM31,
    ref numerator_3: QM31,
    ref memory_address_to_id_sum_4: QM31,
    ref numerator_4: QM31,
    ref memory_id_to_big_sum_5: QM31,
    ref numerator_5: QM31,
    ref range_check_7_2_5_sum_6: QM31,
    ref numerator_6: QM31,
    ref memory_address_to_id_sum_7: QM31,
    ref numerator_7: QM31,
    ref memory_id_to_big_sum_8: QM31,
    ref numerator_8: QM31,
    ref range_check_7_2_5_sum_9: QM31,
    ref numerator_9: QM31,
    ref memory_address_to_id_sum_10: QM31,
    ref numerator_10: QM31,
    ref memory_id_to_big_sum_11: QM31,
    ref numerator_11: QM31,
    ref range_check_7_2_5_sum_12: QM31,
    ref numerator_12: QM31,
    ref memory_address_to_id_sum_13: QM31,
    ref numerator_13: QM31,
    ref memory_id_to_big_sum_14: QM31,
    ref numerator_14: QM31,
    ref range_check_7_2_5_sum_15: QM31,
    ref numerator_15: QM31,
    ref memory_address_to_id_sum_16: QM31,
    ref numerator_16: QM31,
    ref memory_id_to_big_sum_17: QM31,
    ref numerator_17: QM31,
    ref range_check_7_2_5_sum_18: QM31,
    ref numerator_18: QM31,
    ref memory_address_to_id_sum_19: QM31,
    ref numerator_19: QM31,
    ref memory_id_to_big_sum_20: QM31,
    ref numerator_20: QM31,
    ref range_check_7_2_5_sum_21: QM31,
    ref numerator_21: QM31,
    ref memory_address_to_id_sum_22: QM31,
    ref numerator_22: QM31,
    ref memory_id_to_big_sum_23: QM31,
    ref numerator_23: QM31,
    ref verify_bitwise_xor_8_sum_24: QM31,
    ref numerator_24: QM31,
    ref verify_bitwise_xor_8_sum_25: QM31,
    ref numerator_25: QM31,
    ref verify_bitwise_xor_8_sum_26: QM31,
    ref numerator_26: QM31,
    ref verify_bitwise_xor_8_sum_27: QM31,
    ref numerator_27: QM31,
    ref sum: QM31,
    random_coeff: QM31,
) -> [QM31; 4] {
    let [
        create_blake_round_input_input_limb_0,
        create_blake_round_input_input_limb_1,
        create_blake_round_input_input_limb_2,
        create_blake_round_input_input_limb_3,
    ] =
        input;
    read_u_32_evaluate(
        create_blake_round_input_input_limb_0,
        low_16_bits_col0,
        high_16_bits_col1,
        low_7_ms_bits_col2,
        high_14_ms_bits_col3,
        high_5_ms_bits_col4,
        state_0_id_col5,
        common_lookup_elements,
        ref range_check_7_2_5_sum_0,
        ref numerator_0,
        ref memory_address_to_id_sum_1,
        ref numerator_1,
        ref memory_id_to_big_sum_2,
        ref numerator_2,
        ref sum,
        random_coeff,
    );
    read_u_32_evaluate(
        (create_blake_round_input_input_limb_0 + qm31_const::<1, 0, 0, 0>()),
        low_16_bits_col6,
        high_16_bits_col7,
        low_7_ms_bits_col8,
        high_14_ms_bits_col9,
        high_5_ms_bits_col10,
        state_1_id_col11,
        common_lookup_elements,
        ref range_check_7_2_5_sum_3,
        ref numerator_3,
        ref memory_address_to_id_sum_4,
        ref numerator_4,
        ref memory_id_to_big_sum_5,
        ref numerator_5,
        ref sum,
        random_coeff,
    );
    read_u_32_evaluate(
        (create_blake_round_input_input_limb_0 + qm31_const::<2, 0, 0, 0>()),
        low_16_bits_col12,
        high_16_bits_col13,
        low_7_ms_bits_col14,
        high_14_ms_bits_col15,
        high_5_ms_bits_col16,
        state_2_id_col17,
        common_lookup_elements,
        ref range_check_7_2_5_sum_6,
        ref numerator_6,
        ref memory_address_to_id_sum_7,
        ref numerator_7,
        ref memory_id_to_big_sum_8,
        ref numerator_8,
        ref sum,
        random_coeff,
    );
    read_u_32_evaluate(
        (create_blake_round_input_input_limb_0 + qm31_const::<3, 0, 0, 0>()),
        low_16_bits_col18,
        high_16_bits_col19,
        low_7_ms_bits_col20,
        high_14_ms_bits_col21,
        high_5_ms_bits_col22,
        state_3_id_col23,
        common_lookup_elements,
        ref range_check_7_2_5_sum_9,
        ref numerator_9,
        ref memory_address_to_id_sum_10,
        ref numerator_10,
        ref memory_id_to_big_sum_11,
        ref numerator_11,
        ref sum,
        random_coeff,
    );
    read_u_32_evaluate(
        (create_blake_round_input_input_limb_0 + qm31_const::<4, 0, 0, 0>()),
        low_16_bits_col24,
        high_16_bits_col25,
        low_7_ms_bits_col26,
        high_14_ms_bits_col27,
        high_5_ms_bits_col28,
        state_4_id_col29,
        common_lookup_elements,
        ref range_check_7_2_5_sum_12,
        ref numerator_12,
        ref memory_address_to_id_sum_13,
        ref numerator_13,
        ref memory_id_to_big_sum_14,
        ref numerator_14,
        ref sum,
        random_coeff,
    );
    read_u_32_evaluate(
        (create_blake_round_input_input_limb_0 + qm31_const::<5, 0, 0, 0>()),
        low_16_bits_col30,
        high_16_bits_col31,
        low_7_ms_bits_col32,
        high_14_ms_bits_col33,
        high_5_ms_bits_col34,
        state_5_id_col35,
        common_lookup_elements,
        ref range_check_7_2_5_sum_15,
        ref numerator_15,
        ref memory_address_to_id_sum_16,
        ref numerator_16,
        ref memory_id_to_big_sum_17,
        ref numerator_17,
        ref sum,
        random_coeff,
    );
    read_u_32_evaluate(
        (create_blake_round_input_input_limb_0 + qm31_const::<6, 0, 0, 0>()),
        low_16_bits_col36,
        high_16_bits_col37,
        low_7_ms_bits_col38,
        high_14_ms_bits_col39,
        high_5_ms_bits_col40,
        state_6_id_col41,
        common_lookup_elements,
        ref range_check_7_2_5_sum_18,
        ref numerator_18,
        ref memory_address_to_id_sum_19,
        ref numerator_19,
        ref memory_id_to_big_sum_20,
        ref numerator_20,
        ref sum,
        random_coeff,
    );
    read_u_32_evaluate(
        (create_blake_round_input_input_limb_0 + qm31_const::<7, 0, 0, 0>()),
        low_16_bits_col42,
        high_16_bits_col43,
        low_7_ms_bits_col44,
        high_14_ms_bits_col45,
        high_5_ms_bits_col46,
        state_7_id_col47,
        common_lookup_elements,
        ref range_check_7_2_5_sum_21,
        ref numerator_21,
        ref memory_address_to_id_sum_22,
        ref numerator_22,
        ref memory_id_to_big_sum_23,
        ref numerator_23,
        ref sum,
        random_coeff,
    );
    let split_16_low_part_size_8_output_tmp_f95c3_89_limb_0: QM31 =
        split_16_low_part_size_8_evaluate(
        create_blake_round_input_input_limb_1,
        ms_8_bits_col48,
        common_lookup_elements,
        ref sum,
        random_coeff,
    );
    let split_16_low_part_size_8_output_tmp_f95c3_91_limb_0: QM31 =
        split_16_low_part_size_8_evaluate(
        create_blake_round_input_input_limb_2,
        ms_8_bits_col49,
        common_lookup_elements,
        ref sum,
        random_coeff,
    );
    bitwise_xor_num_bits_8_evaluate(
        [split_16_low_part_size_8_output_tmp_f95c3_89_limb_0, qm31_const::<127, 0, 0, 0>()],
        xor_col50,
        common_lookup_elements,
        ref verify_bitwise_xor_8_sum_24,
        ref numerator_24,
        ref sum,
        random_coeff,
    );
    bitwise_xor_num_bits_8_evaluate(
        [ms_8_bits_col48, qm31_const::<82, 0, 0, 0>()],
        xor_col51,
        common_lookup_elements,
        ref verify_bitwise_xor_8_sum_25,
        ref numerator_25,
        ref sum,
        random_coeff,
    );
    bitwise_xor_num_bits_8_evaluate(
        [split_16_low_part_size_8_output_tmp_f95c3_91_limb_0, qm31_const::<14, 0, 0, 0>()],
        xor_col52,
        common_lookup_elements,
        ref verify_bitwise_xor_8_sum_26,
        ref numerator_26,
        ref sum,
        random_coeff,
    );
    bitwise_xor_num_bits_8_evaluate(
        [ms_8_bits_col49, qm31_const::<81, 0, 0, 0>()],
        xor_col53,
        common_lookup_elements,
        ref verify_bitwise_xor_8_sum_27,
        ref numerator_27,
        ref sum,
        random_coeff,
    );

    [
        (xor_col50 + (xor_col51 * qm31_const::<256, 0, 0, 0>())),
        (xor_col52 + (xor_col53 * qm31_const::<256, 0, 0, 0>())),
        ((create_blake_round_input_input_limb_3 * qm31_const::<9812, 0, 0, 0>())
            + ((qm31_const::<1, 0, 0, 0>() - create_blake_round_input_input_limb_3)
                * qm31_const::<55723, 0, 0, 0>())),
        ((create_blake_round_input_input_limb_3 * qm31_const::<57468, 0, 0, 0>())
            + ((qm31_const::<1, 0, 0, 0>() - create_blake_round_input_input_limb_3)
                * qm31_const::<8067, 0, 0, 0>())),
    ]
}
