// This file was created by the AIR team.

use crate::components::subroutines::linear_combination_n_1_coefs_2::linear_combination_n_1_coefs_2_evaluate;
use crate::components::subroutines::linear_combination_n_6_coefs_4_2_3_1_m1_1::linear_combination_n_6_coefs_4_2_3_1_m1_1_evaluate;
use crate::prelude::*;


pub fn poseidon_partial_round_evaluate(
    input: [QM31; 50],
    cube_252_output_limb_0_col0: QM31,
    cube_252_output_limb_1_col1: QM31,
    cube_252_output_limb_2_col2: QM31,
    cube_252_output_limb_3_col3: QM31,
    cube_252_output_limb_4_col4: QM31,
    cube_252_output_limb_5_col5: QM31,
    cube_252_output_limb_6_col6: QM31,
    cube_252_output_limb_7_col7: QM31,
    cube_252_output_limb_8_col8: QM31,
    cube_252_output_limb_9_col9: QM31,
    combination_limb_0_col10: QM31,
    combination_limb_1_col11: QM31,
    combination_limb_2_col12: QM31,
    combination_limb_3_col13: QM31,
    combination_limb_4_col14: QM31,
    combination_limb_5_col15: QM31,
    combination_limb_6_col16: QM31,
    combination_limb_7_col17: QM31,
    combination_limb_8_col18: QM31,
    combination_limb_9_col19: QM31,
    p_coef_col20: QM31,
    combination_limb_0_col21: QM31,
    combination_limb_1_col22: QM31,
    combination_limb_2_col23: QM31,
    combination_limb_3_col24: QM31,
    combination_limb_4_col25: QM31,
    combination_limb_5_col26: QM31,
    combination_limb_6_col27: QM31,
    combination_limb_7_col28: QM31,
    combination_limb_8_col29: QM31,
    combination_limb_9_col30: QM31,
    p_coef_col31: QM31,
    cube_252_lookup_elements: @crate::Cube252Elements,
    range_check_4_4_4_4_lookup_elements: @crate::RangeCheck_4_4_4_4Elements,
    range_check_4_4_lookup_elements: @crate::RangeCheck_4_4Elements,
    range_check_252_width_27_lookup_elements: @crate::RangeCheck252Width27Elements,
    ref cube_252_sum_0: QM31,
    ref range_check_4_4_4_4_sum_1: QM31,
    ref range_check_4_4_4_4_sum_2: QM31,
    ref range_check_4_4_sum_3: QM31,
    ref range_check_252_width_27_sum_4: QM31,
    ref sum: QM31,
    domain_vanishing_eval_inv: QM31,
    random_coeff: QM31,
) -> [QM31; 0] {
    let [
        poseidon_partial_round_input_z0_3_limb_0,
        poseidon_partial_round_input_z0_3_limb_1,
        poseidon_partial_round_input_z0_3_limb_2,
        poseidon_partial_round_input_z0_3_limb_3,
        poseidon_partial_round_input_z0_3_limb_4,
        poseidon_partial_round_input_z0_3_limb_5,
        poseidon_partial_round_input_z0_3_limb_6,
        poseidon_partial_round_input_z0_3_limb_7,
        poseidon_partial_round_input_z0_3_limb_8,
        poseidon_partial_round_input_z0_3_limb_9,
        poseidon_partial_round_input_z1_limb_0,
        poseidon_partial_round_input_z1_limb_1,
        poseidon_partial_round_input_z1_limb_2,
        poseidon_partial_round_input_z1_limb_3,
        poseidon_partial_round_input_z1_limb_4,
        poseidon_partial_round_input_z1_limb_5,
        poseidon_partial_round_input_z1_limb_6,
        poseidon_partial_round_input_z1_limb_7,
        poseidon_partial_round_input_z1_limb_8,
        poseidon_partial_round_input_z1_limb_9,
        poseidon_partial_round_input_z1_3_limb_0,
        poseidon_partial_round_input_z1_3_limb_1,
        poseidon_partial_round_input_z1_3_limb_2,
        poseidon_partial_round_input_z1_3_limb_3,
        poseidon_partial_round_input_z1_3_limb_4,
        poseidon_partial_round_input_z1_3_limb_5,
        poseidon_partial_round_input_z1_3_limb_6,
        poseidon_partial_round_input_z1_3_limb_7,
        poseidon_partial_round_input_z1_3_limb_8,
        poseidon_partial_round_input_z1_3_limb_9,
        poseidon_partial_round_input_z2_limb_0,
        poseidon_partial_round_input_z2_limb_1,
        poseidon_partial_round_input_z2_limb_2,
        poseidon_partial_round_input_z2_limb_3,
        poseidon_partial_round_input_z2_limb_4,
        poseidon_partial_round_input_z2_limb_5,
        poseidon_partial_round_input_z2_limb_6,
        poseidon_partial_round_input_z2_limb_7,
        poseidon_partial_round_input_z2_limb_8,
        poseidon_partial_round_input_z2_limb_9,
        poseidon_partial_round_input_half_key_limb_0,
        poseidon_partial_round_input_half_key_limb_1,
        poseidon_partial_round_input_half_key_limb_2,
        poseidon_partial_round_input_half_key_limb_3,
        poseidon_partial_round_input_half_key_limb_4,
        poseidon_partial_round_input_half_key_limb_5,
        poseidon_partial_round_input_half_key_limb_6,
        poseidon_partial_round_input_half_key_limb_7,
        poseidon_partial_round_input_half_key_limb_8,
        poseidon_partial_round_input_half_key_limb_9,
    ] =
        input;

    cube_252_sum_0 = cube_252_lookup_elements
        .combine_qm31(
            [
                poseidon_partial_round_input_z2_limb_0, poseidon_partial_round_input_z2_limb_1,
                poseidon_partial_round_input_z2_limb_2, poseidon_partial_round_input_z2_limb_3,
                poseidon_partial_round_input_z2_limb_4, poseidon_partial_round_input_z2_limb_5,
                poseidon_partial_round_input_z2_limb_6, poseidon_partial_round_input_z2_limb_7,
                poseidon_partial_round_input_z2_limb_8, poseidon_partial_round_input_z2_limb_9,
                cube_252_output_limb_0_col0, cube_252_output_limb_1_col1,
                cube_252_output_limb_2_col2, cube_252_output_limb_3_col3,
                cube_252_output_limb_4_col4, cube_252_output_limb_5_col5,
                cube_252_output_limb_6_col6, cube_252_output_limb_7_col7,
                cube_252_output_limb_8_col8, cube_252_output_limb_9_col9,
            ],
        );
    linear_combination_n_6_coefs_4_2_3_1_m1_1_evaluate(
        [
            poseidon_partial_round_input_z0_3_limb_0, poseidon_partial_round_input_z0_3_limb_1,
            poseidon_partial_round_input_z0_3_limb_2, poseidon_partial_round_input_z0_3_limb_3,
            poseidon_partial_round_input_z0_3_limb_4, poseidon_partial_round_input_z0_3_limb_5,
            poseidon_partial_round_input_z0_3_limb_6, poseidon_partial_round_input_z0_3_limb_7,
            poseidon_partial_round_input_z0_3_limb_8, poseidon_partial_round_input_z0_3_limb_9,
            poseidon_partial_round_input_z1_limb_0, poseidon_partial_round_input_z1_limb_1,
            poseidon_partial_round_input_z1_limb_2, poseidon_partial_round_input_z1_limb_3,
            poseidon_partial_round_input_z1_limb_4, poseidon_partial_round_input_z1_limb_5,
            poseidon_partial_round_input_z1_limb_6, poseidon_partial_round_input_z1_limb_7,
            poseidon_partial_round_input_z1_limb_8, poseidon_partial_round_input_z1_limb_9,
            poseidon_partial_round_input_z1_3_limb_0, poseidon_partial_round_input_z1_3_limb_1,
            poseidon_partial_round_input_z1_3_limb_2, poseidon_partial_round_input_z1_3_limb_3,
            poseidon_partial_round_input_z1_3_limb_4, poseidon_partial_round_input_z1_3_limb_5,
            poseidon_partial_round_input_z1_3_limb_6, poseidon_partial_round_input_z1_3_limb_7,
            poseidon_partial_round_input_z1_3_limb_8, poseidon_partial_round_input_z1_3_limb_9,
            poseidon_partial_round_input_z2_limb_0, poseidon_partial_round_input_z2_limb_1,
            poseidon_partial_round_input_z2_limb_2, poseidon_partial_round_input_z2_limb_3,
            poseidon_partial_round_input_z2_limb_4, poseidon_partial_round_input_z2_limb_5,
            poseidon_partial_round_input_z2_limb_6, poseidon_partial_round_input_z2_limb_7,
            poseidon_partial_round_input_z2_limb_8, poseidon_partial_round_input_z2_limb_9,
            cube_252_output_limb_0_col0, cube_252_output_limb_1_col1, cube_252_output_limb_2_col2,
            cube_252_output_limb_3_col3, cube_252_output_limb_4_col4, cube_252_output_limb_5_col5,
            cube_252_output_limb_6_col6, cube_252_output_limb_7_col7, cube_252_output_limb_8_col8,
            cube_252_output_limb_9_col9, poseidon_partial_round_input_half_key_limb_0,
            poseidon_partial_round_input_half_key_limb_1,
            poseidon_partial_round_input_half_key_limb_2,
            poseidon_partial_round_input_half_key_limb_3,
            poseidon_partial_round_input_half_key_limb_4,
            poseidon_partial_round_input_half_key_limb_5,
            poseidon_partial_round_input_half_key_limb_6,
            poseidon_partial_round_input_half_key_limb_7,
            poseidon_partial_round_input_half_key_limb_8,
            poseidon_partial_round_input_half_key_limb_9,
        ],
        combination_limb_0_col10,
        combination_limb_1_col11,
        combination_limb_2_col12,
        combination_limb_3_col13,
        combination_limb_4_col14,
        combination_limb_5_col15,
        combination_limb_6_col16,
        combination_limb_7_col17,
        combination_limb_8_col18,
        combination_limb_9_col19,
        p_coef_col20,
        range_check_4_4_4_4_lookup_elements,
        range_check_4_4_lookup_elements,
        ref range_check_4_4_4_4_sum_1,
        ref range_check_4_4_4_4_sum_2,
        ref range_check_4_4_sum_3,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );

    range_check_252_width_27_sum_4 = range_check_252_width_27_lookup_elements
        .combine_qm31(
            [
                combination_limb_0_col10, combination_limb_1_col11, combination_limb_2_col12,
                combination_limb_3_col13, combination_limb_4_col14, combination_limb_5_col15,
                combination_limb_6_col16, combination_limb_7_col17, combination_limb_8_col18,
                combination_limb_9_col19,
            ],
        );
    linear_combination_n_1_coefs_2_evaluate(
        [
            combination_limb_0_col10, combination_limb_1_col11, combination_limb_2_col12,
            combination_limb_3_col13, combination_limb_4_col14, combination_limb_5_col15,
            combination_limb_6_col16, combination_limb_7_col17, combination_limb_8_col18,
            combination_limb_9_col19,
        ],
        combination_limb_0_col21,
        combination_limb_1_col22,
        combination_limb_2_col23,
        combination_limb_3_col24,
        combination_limb_4_col25,
        combination_limb_5_col26,
        combination_limb_6_col27,
        combination_limb_7_col28,
        combination_limb_8_col29,
        combination_limb_9_col30,
        p_coef_col31,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );

    []
}
