use core::num::traits::Zero;
use stwo_constraint_framework::{
    PreprocessedColumn, PreprocessedColumnSet, PreprocessedColumnSetImpl, PreprocessedMaskValues,
    PreprocessedMaskValuesImpl,
};
use stwo_verifier_core::channel::{Channel, ChannelTrait};
use stwo_verifier_core::circle::{
    CirclePoint, CirclePointIndexTrait, CirclePointQM31AddCirclePointM31Trait,
};
use stwo_verifier_core::fields::Invertible;
use stwo_verifier_core::fields::m31::{M31, m31};
use stwo_verifier_core::fields::qm31::{
    QM31, QM31Impl, QM31Serde, QM31Zero, QM31_EXTENSION_DEGREE, qm31_const,
};
use stwo_verifier_core::poly::circle::CanonicCosetImpl;
use stwo_verifier_core::utils::{ArrayImpl, pow2};
use stwo_verifier_core::{ColumnArray, ColumnSpan, TreeArray};
use crate::components::memory_address_to_id::{
    MEMORY_ADDRESS_TO_ID_RELATION_SIZE, memory_address_to_id_sum,
};
use crate::components::memory_id_to_big::{MEMORY_ID_TO_BIG_RELATION_SIZE, memory_id_to_big_sum};
use crate::components::range_check_7_2_5::{RANGE_CHECK_7_2_5_RELATION_SIZE, range_check_7_2_5_sum};
use crate::components::subroutines::read_blake_word::read_blake_word_evaluate;
use crate::components::{CairoComponent, OPCODES_RELATION_SIZE, opcodes_sum};
use crate::utils::U32Impl;


pub const N_TRACE_COLUMNS: usize = 96;


pub fn read_blake_words_evaluate(
    input: [QM31; 17],
    low_16_bits_col0: QM31,
    high_16_bits_col1: QM31,
    low_7_ms_bits_col2: QM31,
    high_14_ms_bits_col3: QM31,
    high_5_ms_bits_col4: QM31,
    message_word_0_id_col5: QM31,
    low_16_bits_col6: QM31,
    high_16_bits_col7: QM31,
    low_7_ms_bits_col8: QM31,
    high_14_ms_bits_col9: QM31,
    high_5_ms_bits_col10: QM31,
    message_word_1_id_col11: QM31,
    low_16_bits_col12: QM31,
    high_16_bits_col13: QM31,
    low_7_ms_bits_col14: QM31,
    high_14_ms_bits_col15: QM31,
    high_5_ms_bits_col16: QM31,
    message_word_2_id_col17: QM31,
    low_16_bits_col18: QM31,
    high_16_bits_col19: QM31,
    low_7_ms_bits_col20: QM31,
    high_14_ms_bits_col21: QM31,
    high_5_ms_bits_col22: QM31,
    message_word_3_id_col23: QM31,
    low_16_bits_col24: QM31,
    high_16_bits_col25: QM31,
    low_7_ms_bits_col26: QM31,
    high_14_ms_bits_col27: QM31,
    high_5_ms_bits_col28: QM31,
    message_word_4_id_col29: QM31,
    low_16_bits_col30: QM31,
    high_16_bits_col31: QM31,
    low_7_ms_bits_col32: QM31,
    high_14_ms_bits_col33: QM31,
    high_5_ms_bits_col34: QM31,
    message_word_5_id_col35: QM31,
    low_16_bits_col36: QM31,
    high_16_bits_col37: QM31,
    low_7_ms_bits_col38: QM31,
    high_14_ms_bits_col39: QM31,
    high_5_ms_bits_col40: QM31,
    message_word_6_id_col41: QM31,
    low_16_bits_col42: QM31,
    high_16_bits_col43: QM31,
    low_7_ms_bits_col44: QM31,
    high_14_ms_bits_col45: QM31,
    high_5_ms_bits_col46: QM31,
    message_word_7_id_col47: QM31,
    low_16_bits_col48: QM31,
    high_16_bits_col49: QM31,
    low_7_ms_bits_col50: QM31,
    high_14_ms_bits_col51: QM31,
    high_5_ms_bits_col52: QM31,
    message_word_8_id_col53: QM31,
    low_16_bits_col54: QM31,
    high_16_bits_col55: QM31,
    low_7_ms_bits_col56: QM31,
    high_14_ms_bits_col57: QM31,
    high_5_ms_bits_col58: QM31,
    message_word_9_id_col59: QM31,
    low_16_bits_col60: QM31,
    high_16_bits_col61: QM31,
    low_7_ms_bits_col62: QM31,
    high_14_ms_bits_col63: QM31,
    high_5_ms_bits_col64: QM31,
    message_word_10_id_col65: QM31,
    low_16_bits_col66: QM31,
    high_16_bits_col67: QM31,
    low_7_ms_bits_col68: QM31,
    high_14_ms_bits_col69: QM31,
    high_5_ms_bits_col70: QM31,
    message_word_11_id_col71: QM31,
    low_16_bits_col72: QM31,
    high_16_bits_col73: QM31,
    low_7_ms_bits_col74: QM31,
    high_14_ms_bits_col75: QM31,
    high_5_ms_bits_col76: QM31,
    message_word_12_id_col77: QM31,
    low_16_bits_col78: QM31,
    high_16_bits_col79: QM31,
    low_7_ms_bits_col80: QM31,
    high_14_ms_bits_col81: QM31,
    high_5_ms_bits_col82: QM31,
    message_word_13_id_col83: QM31,
    low_16_bits_col84: QM31,
    high_16_bits_col85: QM31,
    low_7_ms_bits_col86: QM31,
    high_14_ms_bits_col87: QM31,
    high_5_ms_bits_col88: QM31,
    message_word_14_id_col89: QM31,
    low_16_bits_col90: QM31,
    high_16_bits_col91: QM31,
    low_7_ms_bits_col92: QM31,
    high_14_ms_bits_col93: QM31,
    high_5_ms_bits_col94: QM31,
    message_word_15_id_col95: QM31,
    range_check_7_2_5_alphas: Span<QM31>,
    range_check_7_2_5_z: QM31,
    memory_address_to_id_alphas: Span<QM31>,
    memory_address_to_id_z: QM31,
    memory_id_to_big_alphas: Span<QM31>,
    memory_id_to_big_z: QM31,
    ref range_check_7_2_5_sum_0: QM31,
    ref memory_address_to_id_sum_1: QM31,
    ref memory_id_to_big_sum_2: QM31,
    ref range_check_7_2_5_sum_3: QM31,
    ref memory_address_to_id_sum_4: QM31,
    ref memory_id_to_big_sum_5: QM31,
    ref range_check_7_2_5_sum_6: QM31,
    ref memory_address_to_id_sum_7: QM31,
    ref memory_id_to_big_sum_8: QM31,
    ref range_check_7_2_5_sum_9: QM31,
    ref memory_address_to_id_sum_10: QM31,
    ref memory_id_to_big_sum_11: QM31,
    ref range_check_7_2_5_sum_12: QM31,
    ref memory_address_to_id_sum_13: QM31,
    ref memory_id_to_big_sum_14: QM31,
    ref range_check_7_2_5_sum_15: QM31,
    ref memory_address_to_id_sum_16: QM31,
    ref memory_id_to_big_sum_17: QM31,
    ref range_check_7_2_5_sum_18: QM31,
    ref memory_address_to_id_sum_19: QM31,
    ref memory_id_to_big_sum_20: QM31,
    ref range_check_7_2_5_sum_21: QM31,
    ref memory_address_to_id_sum_22: QM31,
    ref memory_id_to_big_sum_23: QM31,
    ref range_check_7_2_5_sum_24: QM31,
    ref memory_address_to_id_sum_25: QM31,
    ref memory_id_to_big_sum_26: QM31,
    ref range_check_7_2_5_sum_27: QM31,
    ref memory_address_to_id_sum_28: QM31,
    ref memory_id_to_big_sum_29: QM31,
    ref range_check_7_2_5_sum_30: QM31,
    ref memory_address_to_id_sum_31: QM31,
    ref memory_id_to_big_sum_32: QM31,
    ref range_check_7_2_5_sum_33: QM31,
    ref memory_address_to_id_sum_34: QM31,
    ref memory_id_to_big_sum_35: QM31,
    ref range_check_7_2_5_sum_36: QM31,
    ref memory_address_to_id_sum_37: QM31,
    ref memory_id_to_big_sum_38: QM31,
    ref range_check_7_2_5_sum_39: QM31,
    ref memory_address_to_id_sum_40: QM31,
    ref memory_id_to_big_sum_41: QM31,
    ref range_check_7_2_5_sum_42: QM31,
    ref memory_address_to_id_sum_43: QM31,
    ref memory_id_to_big_sum_44: QM31,
    ref range_check_7_2_5_sum_45: QM31,
    ref memory_address_to_id_sum_46: QM31,
    ref memory_id_to_big_sum_47: QM31,
    ref sum: QM31,
    domain_vanishing_eval_inv: QM31,
    random_coeff: QM31,
) -> [QM31; 32] {
    let [
        read_blake_words_input_limb_0,
        read_blake_words_input_limb_1,
        read_blake_words_input_limb_2,
        read_blake_words_input_limb_3,
        read_blake_words_input_limb_4,
        read_blake_words_input_limb_5,
        read_blake_words_input_limb_6,
        read_blake_words_input_limb_7,
        read_blake_words_input_limb_8,
        read_blake_words_input_limb_9,
        read_blake_words_input_limb_10,
        read_blake_words_input_limb_11,
        read_blake_words_input_limb_12,
        read_blake_words_input_limb_13,
        read_blake_words_input_limb_14,
        read_blake_words_input_limb_15,
        read_blake_words_input_limb_16,
    ] =
        input;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_1),
        low_16_bits_col0,
        high_16_bits_col1,
        low_7_ms_bits_col2,
        high_14_ms_bits_col3,
        high_5_ms_bits_col4,
        message_word_0_id_col5,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_0,
        ref memory_address_to_id_sum_1,
        ref memory_id_to_big_sum_2,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_8_limb_0, read_blake_word_output_tmp_355a4_8_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_2),
        low_16_bits_col6,
        high_16_bits_col7,
        low_7_ms_bits_col8,
        high_14_ms_bits_col9,
        high_5_ms_bits_col10,
        message_word_1_id_col11,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_3,
        ref memory_address_to_id_sum_4,
        ref memory_id_to_big_sum_5,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_17_limb_0, read_blake_word_output_tmp_355a4_17_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_3),
        low_16_bits_col12,
        high_16_bits_col13,
        low_7_ms_bits_col14,
        high_14_ms_bits_col15,
        high_5_ms_bits_col16,
        message_word_2_id_col17,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_6,
        ref memory_address_to_id_sum_7,
        ref memory_id_to_big_sum_8,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_26_limb_0, read_blake_word_output_tmp_355a4_26_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_4),
        low_16_bits_col18,
        high_16_bits_col19,
        low_7_ms_bits_col20,
        high_14_ms_bits_col21,
        high_5_ms_bits_col22,
        message_word_3_id_col23,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_9,
        ref memory_address_to_id_sum_10,
        ref memory_id_to_big_sum_11,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_35_limb_0, read_blake_word_output_tmp_355a4_35_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_5),
        low_16_bits_col24,
        high_16_bits_col25,
        low_7_ms_bits_col26,
        high_14_ms_bits_col27,
        high_5_ms_bits_col28,
        message_word_4_id_col29,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_12,
        ref memory_address_to_id_sum_13,
        ref memory_id_to_big_sum_14,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_44_limb_0, read_blake_word_output_tmp_355a4_44_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_6),
        low_16_bits_col30,
        high_16_bits_col31,
        low_7_ms_bits_col32,
        high_14_ms_bits_col33,
        high_5_ms_bits_col34,
        message_word_5_id_col35,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_15,
        ref memory_address_to_id_sum_16,
        ref memory_id_to_big_sum_17,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_53_limb_0, read_blake_word_output_tmp_355a4_53_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_7),
        low_16_bits_col36,
        high_16_bits_col37,
        low_7_ms_bits_col38,
        high_14_ms_bits_col39,
        high_5_ms_bits_col40,
        message_word_6_id_col41,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_18,
        ref memory_address_to_id_sum_19,
        ref memory_id_to_big_sum_20,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_62_limb_0, read_blake_word_output_tmp_355a4_62_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_8),
        low_16_bits_col42,
        high_16_bits_col43,
        low_7_ms_bits_col44,
        high_14_ms_bits_col45,
        high_5_ms_bits_col46,
        message_word_7_id_col47,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_21,
        ref memory_address_to_id_sum_22,
        ref memory_id_to_big_sum_23,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_71_limb_0, read_blake_word_output_tmp_355a4_71_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_9),
        low_16_bits_col48,
        high_16_bits_col49,
        low_7_ms_bits_col50,
        high_14_ms_bits_col51,
        high_5_ms_bits_col52,
        message_word_8_id_col53,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_24,
        ref memory_address_to_id_sum_25,
        ref memory_id_to_big_sum_26,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_80_limb_0, read_blake_word_output_tmp_355a4_80_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_10),
        low_16_bits_col54,
        high_16_bits_col55,
        low_7_ms_bits_col56,
        high_14_ms_bits_col57,
        high_5_ms_bits_col58,
        message_word_9_id_col59,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_27,
        ref memory_address_to_id_sum_28,
        ref memory_id_to_big_sum_29,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_89_limb_0, read_blake_word_output_tmp_355a4_89_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_11),
        low_16_bits_col60,
        high_16_bits_col61,
        low_7_ms_bits_col62,
        high_14_ms_bits_col63,
        high_5_ms_bits_col64,
        message_word_10_id_col65,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_30,
        ref memory_address_to_id_sum_31,
        ref memory_id_to_big_sum_32,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_98_limb_0, read_blake_word_output_tmp_355a4_98_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_12),
        low_16_bits_col66,
        high_16_bits_col67,
        low_7_ms_bits_col68,
        high_14_ms_bits_col69,
        high_5_ms_bits_col70,
        message_word_11_id_col71,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_33,
        ref memory_address_to_id_sum_34,
        ref memory_id_to_big_sum_35,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_107_limb_0, read_blake_word_output_tmp_355a4_107_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_13),
        low_16_bits_col72,
        high_16_bits_col73,
        low_7_ms_bits_col74,
        high_14_ms_bits_col75,
        high_5_ms_bits_col76,
        message_word_12_id_col77,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_36,
        ref memory_address_to_id_sum_37,
        ref memory_id_to_big_sum_38,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_116_limb_0, read_blake_word_output_tmp_355a4_116_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_14),
        low_16_bits_col78,
        high_16_bits_col79,
        low_7_ms_bits_col80,
        high_14_ms_bits_col81,
        high_5_ms_bits_col82,
        message_word_13_id_col83,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_39,
        ref memory_address_to_id_sum_40,
        ref memory_id_to_big_sum_41,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_125_limb_0, read_blake_word_output_tmp_355a4_125_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_15),
        low_16_bits_col84,
        high_16_bits_col85,
        low_7_ms_bits_col86,
        high_14_ms_bits_col87,
        high_5_ms_bits_col88,
        message_word_14_id_col89,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_42,
        ref memory_address_to_id_sum_43,
        ref memory_id_to_big_sum_44,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_134_limb_0, read_blake_word_output_tmp_355a4_134_limb_1] =
        output;

    let output: [QM31; 2] = read_blake_word_evaluate(
        (read_blake_words_input_limb_0 + read_blake_words_input_limb_16),
        low_16_bits_col90,
        high_16_bits_col91,
        low_7_ms_bits_col92,
        high_14_ms_bits_col93,
        high_5_ms_bits_col94,
        message_word_15_id_col95,
        range_check_7_2_5_alphas,
        range_check_7_2_5_z,
        memory_address_to_id_alphas,
        memory_address_to_id_z,
        memory_id_to_big_alphas,
        memory_id_to_big_z,
        ref range_check_7_2_5_sum_45,
        ref memory_address_to_id_sum_46,
        ref memory_id_to_big_sum_47,
        ref sum,
        domain_vanishing_eval_inv,
        random_coeff,
    );
    let [read_blake_word_output_tmp_355a4_143_limb_0, read_blake_word_output_tmp_355a4_143_limb_1] =
        output;

    [
        low_16_bits_col0, high_16_bits_col1, low_16_bits_col6, high_16_bits_col7, low_16_bits_col12,
        high_16_bits_col13, low_16_bits_col18, high_16_bits_col19, low_16_bits_col24,
        high_16_bits_col25, low_16_bits_col30, high_16_bits_col31, low_16_bits_col36,
        high_16_bits_col37, low_16_bits_col42, high_16_bits_col43, low_16_bits_col48,
        high_16_bits_col49, low_16_bits_col54, high_16_bits_col55, low_16_bits_col60,
        high_16_bits_col61, low_16_bits_col66, high_16_bits_col67, low_16_bits_col72,
        high_16_bits_col73, low_16_bits_col78, high_16_bits_col79, low_16_bits_col84,
        high_16_bits_col85, low_16_bits_col90, high_16_bits_col91,
    ]
}
