# See: https://rust-lang.github.io/rustfmt
normalize_comments = true
use_field_init_shorthand = true

# Unstable
comment_width = 100
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
unstable_features = true
wrap_comments = true
