pub const N_M31_IN_SMALL_FELT252: usize = 8;
pub const LOG_MEMORY_ADDRESS_BOUND: u32 = 29;
pub const MEMORY_ADDRESS_BOUND: usize = 1 << LOG_MEMORY_ADDRESS_BOUND;
pub const LARGE_MEMORY_VALUE_ID_BASE: u32 = 0x4000_0000;
pub const FELT252_BITS_PER_WORD: usize = 9;
