// This file was created by the AIR team.

use crate::components::prelude::*;
use crate::components::subroutines::range_check_mem_value_n_28::RangeCheckMemValueN28;
use crate::components::subroutines::verify_mul_252::VerifyMul252;

#[derive(Copy, Clone, Serialize, Deserialize, CairoSerialize)]
pub struct EcAdd {}

impl EcAdd {
    #[allow(unused_parens)]
    #[allow(clippy::double_parens)]
    #[allow(non_snake_case)]
    #[allow(clippy::unused_unit)]
    #[allow(unused_variables)]
    #[allow(clippy::too_many_arguments)]
    pub fn evaluate<E: EvalAtRow>(
        [ec_add_input_x1_limb_0, ec_add_input_x1_limb_1, ec_add_input_x1_limb_2, ec_add_input_x1_limb_3, ec_add_input_x1_limb_4, ec_add_input_x1_limb_5, ec_add_input_x1_limb_6, ec_add_input_x1_limb_7, ec_add_input_x1_limb_8, ec_add_input_x1_limb_9, ec_add_input_x1_limb_10, ec_add_input_x1_limb_11, ec_add_input_x1_limb_12, ec_add_input_x1_limb_13, ec_add_input_x1_limb_14, ec_add_input_x1_limb_15, ec_add_input_x1_limb_16, ec_add_input_x1_limb_17, ec_add_input_x1_limb_18, ec_add_input_x1_limb_19, ec_add_input_x1_limb_20, ec_add_input_x1_limb_21, ec_add_input_x1_limb_22, ec_add_input_x1_limb_23, ec_add_input_x1_limb_24, ec_add_input_x1_limb_25, ec_add_input_x1_limb_26, ec_add_input_x1_limb_27, ec_add_input_y1_limb_0, ec_add_input_y1_limb_1, ec_add_input_y1_limb_2, ec_add_input_y1_limb_3, ec_add_input_y1_limb_4, ec_add_input_y1_limb_5, ec_add_input_y1_limb_6, ec_add_input_y1_limb_7, ec_add_input_y1_limb_8, ec_add_input_y1_limb_9, ec_add_input_y1_limb_10, ec_add_input_y1_limb_11, ec_add_input_y1_limb_12, ec_add_input_y1_limb_13, ec_add_input_y1_limb_14, ec_add_input_y1_limb_15, ec_add_input_y1_limb_16, ec_add_input_y1_limb_17, ec_add_input_y1_limb_18, ec_add_input_y1_limb_19, ec_add_input_y1_limb_20, ec_add_input_y1_limb_21, ec_add_input_y1_limb_22, ec_add_input_y1_limb_23, ec_add_input_y1_limb_24, ec_add_input_y1_limb_25, ec_add_input_y1_limb_26, ec_add_input_y1_limb_27, ec_add_input_x2_limb_0, ec_add_input_x2_limb_1, ec_add_input_x2_limb_2, ec_add_input_x2_limb_3, ec_add_input_x2_limb_4, ec_add_input_x2_limb_5, ec_add_input_x2_limb_6, ec_add_input_x2_limb_7, ec_add_input_x2_limb_8, ec_add_input_x2_limb_9, ec_add_input_x2_limb_10, ec_add_input_x2_limb_11, ec_add_input_x2_limb_12, ec_add_input_x2_limb_13, ec_add_input_x2_limb_14, ec_add_input_x2_limb_15, ec_add_input_x2_limb_16, ec_add_input_x2_limb_17, ec_add_input_x2_limb_18, ec_add_input_x2_limb_19, ec_add_input_x2_limb_20, ec_add_input_x2_limb_21, ec_add_input_x2_limb_22, ec_add_input_x2_limb_23, ec_add_input_x2_limb_24, ec_add_input_x2_limb_25, ec_add_input_x2_limb_26, ec_add_input_x2_limb_27, ec_add_input_y2_limb_0, ec_add_input_y2_limb_1, ec_add_input_y2_limb_2, ec_add_input_y2_limb_3, ec_add_input_y2_limb_4, ec_add_input_y2_limb_5, ec_add_input_y2_limb_6, ec_add_input_y2_limb_7, ec_add_input_y2_limb_8, ec_add_input_y2_limb_9, ec_add_input_y2_limb_10, ec_add_input_y2_limb_11, ec_add_input_y2_limb_12, ec_add_input_y2_limb_13, ec_add_input_y2_limb_14, ec_add_input_y2_limb_15, ec_add_input_y2_limb_16, ec_add_input_y2_limb_17, ec_add_input_y2_limb_18, ec_add_input_y2_limb_19, ec_add_input_y2_limb_20, ec_add_input_y2_limb_21, ec_add_input_y2_limb_22, ec_add_input_y2_limb_23, ec_add_input_y2_limb_24, ec_add_input_y2_limb_25, ec_add_input_y2_limb_26, ec_add_input_y2_limb_27]: [E::F; 112],
        slope_limb_0_col0: E::F,
        slope_limb_1_col1: E::F,
        slope_limb_2_col2: E::F,
        slope_limb_3_col3: E::F,
        slope_limb_4_col4: E::F,
        slope_limb_5_col5: E::F,
        slope_limb_6_col6: E::F,
        slope_limb_7_col7: E::F,
        slope_limb_8_col8: E::F,
        slope_limb_9_col9: E::F,
        slope_limb_10_col10: E::F,
        slope_limb_11_col11: E::F,
        slope_limb_12_col12: E::F,
        slope_limb_13_col13: E::F,
        slope_limb_14_col14: E::F,
        slope_limb_15_col15: E::F,
        slope_limb_16_col16: E::F,
        slope_limb_17_col17: E::F,
        slope_limb_18_col18: E::F,
        slope_limb_19_col19: E::F,
        slope_limb_20_col20: E::F,
        slope_limb_21_col21: E::F,
        slope_limb_22_col22: E::F,
        slope_limb_23_col23: E::F,
        slope_limb_24_col24: E::F,
        slope_limb_25_col25: E::F,
        slope_limb_26_col26: E::F,
        slope_limb_27_col27: E::F,
        k_col28: E::F,
        carry_0_col29: E::F,
        carry_1_col30: E::F,
        carry_2_col31: E::F,
        carry_3_col32: E::F,
        carry_4_col33: E::F,
        carry_5_col34: E::F,
        carry_6_col35: E::F,
        carry_7_col36: E::F,
        carry_8_col37: E::F,
        carry_9_col38: E::F,
        carry_10_col39: E::F,
        carry_11_col40: E::F,
        carry_12_col41: E::F,
        carry_13_col42: E::F,
        carry_14_col43: E::F,
        carry_15_col44: E::F,
        carry_16_col45: E::F,
        carry_17_col46: E::F,
        carry_18_col47: E::F,
        carry_19_col48: E::F,
        carry_20_col49: E::F,
        carry_21_col50: E::F,
        carry_22_col51: E::F,
        carry_23_col52: E::F,
        carry_24_col53: E::F,
        carry_25_col54: E::F,
        carry_26_col55: E::F,
        result_x_limb_0_col56: E::F,
        result_x_limb_1_col57: E::F,
        result_x_limb_2_col58: E::F,
        result_x_limb_3_col59: E::F,
        result_x_limb_4_col60: E::F,
        result_x_limb_5_col61: E::F,
        result_x_limb_6_col62: E::F,
        result_x_limb_7_col63: E::F,
        result_x_limb_8_col64: E::F,
        result_x_limb_9_col65: E::F,
        result_x_limb_10_col66: E::F,
        result_x_limb_11_col67: E::F,
        result_x_limb_12_col68: E::F,
        result_x_limb_13_col69: E::F,
        result_x_limb_14_col70: E::F,
        result_x_limb_15_col71: E::F,
        result_x_limb_16_col72: E::F,
        result_x_limb_17_col73: E::F,
        result_x_limb_18_col74: E::F,
        result_x_limb_19_col75: E::F,
        result_x_limb_20_col76: E::F,
        result_x_limb_21_col77: E::F,
        result_x_limb_22_col78: E::F,
        result_x_limb_23_col79: E::F,
        result_x_limb_24_col80: E::F,
        result_x_limb_25_col81: E::F,
        result_x_limb_26_col82: E::F,
        result_x_limb_27_col83: E::F,
        k_col84: E::F,
        carry_0_col85: E::F,
        carry_1_col86: E::F,
        carry_2_col87: E::F,
        carry_3_col88: E::F,
        carry_4_col89: E::F,
        carry_5_col90: E::F,
        carry_6_col91: E::F,
        carry_7_col92: E::F,
        carry_8_col93: E::F,
        carry_9_col94: E::F,
        carry_10_col95: E::F,
        carry_11_col96: E::F,
        carry_12_col97: E::F,
        carry_13_col98: E::F,
        carry_14_col99: E::F,
        carry_15_col100: E::F,
        carry_16_col101: E::F,
        carry_17_col102: E::F,
        carry_18_col103: E::F,
        carry_19_col104: E::F,
        carry_20_col105: E::F,
        carry_21_col106: E::F,
        carry_22_col107: E::F,
        carry_23_col108: E::F,
        carry_24_col109: E::F,
        carry_25_col110: E::F,
        carry_26_col111: E::F,
        result_y_limb_0_col112: E::F,
        result_y_limb_1_col113: E::F,
        result_y_limb_2_col114: E::F,
        result_y_limb_3_col115: E::F,
        result_y_limb_4_col116: E::F,
        result_y_limb_5_col117: E::F,
        result_y_limb_6_col118: E::F,
        result_y_limb_7_col119: E::F,
        result_y_limb_8_col120: E::F,
        result_y_limb_9_col121: E::F,
        result_y_limb_10_col122: E::F,
        result_y_limb_11_col123: E::F,
        result_y_limb_12_col124: E::F,
        result_y_limb_13_col125: E::F,
        result_y_limb_14_col126: E::F,
        result_y_limb_15_col127: E::F,
        result_y_limb_16_col128: E::F,
        result_y_limb_17_col129: E::F,
        result_y_limb_18_col130: E::F,
        result_y_limb_19_col131: E::F,
        result_y_limb_20_col132: E::F,
        result_y_limb_21_col133: E::F,
        result_y_limb_22_col134: E::F,
        result_y_limb_23_col135: E::F,
        result_y_limb_24_col136: E::F,
        result_y_limb_25_col137: E::F,
        result_y_limb_26_col138: E::F,
        result_y_limb_27_col139: E::F,
        k_col140: E::F,
        carry_0_col141: E::F,
        carry_1_col142: E::F,
        carry_2_col143: E::F,
        carry_3_col144: E::F,
        carry_4_col145: E::F,
        carry_5_col146: E::F,
        carry_6_col147: E::F,
        carry_7_col148: E::F,
        carry_8_col149: E::F,
        carry_9_col150: E::F,
        carry_10_col151: E::F,
        carry_11_col152: E::F,
        carry_12_col153: E::F,
        carry_13_col154: E::F,
        carry_14_col155: E::F,
        carry_15_col156: E::F,
        carry_16_col157: E::F,
        carry_17_col158: E::F,
        carry_18_col159: E::F,
        carry_19_col160: E::F,
        carry_20_col161: E::F,
        carry_21_col162: E::F,
        carry_22_col163: E::F,
        carry_23_col164: E::F,
        carry_24_col165: E::F,
        carry_25_col166: E::F,
        carry_26_col167: E::F,
        range_check_9_9_lookup_elements: &relations::RangeCheck_9_9,
        range_check_9_9_b_lookup_elements: &relations::RangeCheck_9_9_B,
        range_check_9_9_c_lookup_elements: &relations::RangeCheck_9_9_C,
        range_check_9_9_d_lookup_elements: &relations::RangeCheck_9_9_D,
        range_check_9_9_e_lookup_elements: &relations::RangeCheck_9_9_E,
        range_check_9_9_f_lookup_elements: &relations::RangeCheck_9_9_F,
        range_check_9_9_g_lookup_elements: &relations::RangeCheck_9_9_G,
        range_check_9_9_h_lookup_elements: &relations::RangeCheck_9_9_H,
        range_check_20_lookup_elements: &relations::RangeCheck_20,
        range_check_20_b_lookup_elements: &relations::RangeCheck_20_B,
        range_check_20_c_lookup_elements: &relations::RangeCheck_20_C,
        range_check_20_d_lookup_elements: &relations::RangeCheck_20_D,
        range_check_20_e_lookup_elements: &relations::RangeCheck_20_E,
        range_check_20_f_lookup_elements: &relations::RangeCheck_20_F,
        range_check_20_g_lookup_elements: &relations::RangeCheck_20_G,
        range_check_20_h_lookup_elements: &relations::RangeCheck_20_H,
        eval: &mut E,
    ) -> [E::F; 0] {
        RangeCheckMemValueN28::evaluate(
            [
                slope_limb_0_col0.clone(),
                slope_limb_1_col1.clone(),
                slope_limb_2_col2.clone(),
                slope_limb_3_col3.clone(),
                slope_limb_4_col4.clone(),
                slope_limb_5_col5.clone(),
                slope_limb_6_col6.clone(),
                slope_limb_7_col7.clone(),
                slope_limb_8_col8.clone(),
                slope_limb_9_col9.clone(),
                slope_limb_10_col10.clone(),
                slope_limb_11_col11.clone(),
                slope_limb_12_col12.clone(),
                slope_limb_13_col13.clone(),
                slope_limb_14_col14.clone(),
                slope_limb_15_col15.clone(),
                slope_limb_16_col16.clone(),
                slope_limb_17_col17.clone(),
                slope_limb_18_col18.clone(),
                slope_limb_19_col19.clone(),
                slope_limb_20_col20.clone(),
                slope_limb_21_col21.clone(),
                slope_limb_22_col22.clone(),
                slope_limb_23_col23.clone(),
                slope_limb_24_col24.clone(),
                slope_limb_25_col25.clone(),
                slope_limb_26_col26.clone(),
                slope_limb_27_col27.clone(),
            ],
            range_check_9_9_lookup_elements,
            range_check_9_9_b_lookup_elements,
            range_check_9_9_c_lookup_elements,
            range_check_9_9_d_lookup_elements,
            range_check_9_9_e_lookup_elements,
            range_check_9_9_f_lookup_elements,
            range_check_9_9_g_lookup_elements,
            range_check_9_9_h_lookup_elements,
            eval,
        );
        VerifyMul252::evaluate(
            [
                slope_limb_0_col0.clone(),
                slope_limb_1_col1.clone(),
                slope_limb_2_col2.clone(),
                slope_limb_3_col3.clone(),
                slope_limb_4_col4.clone(),
                slope_limb_5_col5.clone(),
                slope_limb_6_col6.clone(),
                slope_limb_7_col7.clone(),
                slope_limb_8_col8.clone(),
                slope_limb_9_col9.clone(),
                slope_limb_10_col10.clone(),
                slope_limb_11_col11.clone(),
                slope_limb_12_col12.clone(),
                slope_limb_13_col13.clone(),
                slope_limb_14_col14.clone(),
                slope_limb_15_col15.clone(),
                slope_limb_16_col16.clone(),
                slope_limb_17_col17.clone(),
                slope_limb_18_col18.clone(),
                slope_limb_19_col19.clone(),
                slope_limb_20_col20.clone(),
                slope_limb_21_col21.clone(),
                slope_limb_22_col22.clone(),
                slope_limb_23_col23.clone(),
                slope_limb_24_col24.clone(),
                slope_limb_25_col25.clone(),
                slope_limb_26_col26.clone(),
                slope_limb_27_col27.clone(),
                (ec_add_input_x2_limb_0.clone() - ec_add_input_x1_limb_0.clone()),
                (ec_add_input_x2_limb_1.clone() - ec_add_input_x1_limb_1.clone()),
                (ec_add_input_x2_limb_2.clone() - ec_add_input_x1_limb_2.clone()),
                (ec_add_input_x2_limb_3.clone() - ec_add_input_x1_limb_3.clone()),
                (ec_add_input_x2_limb_4.clone() - ec_add_input_x1_limb_4.clone()),
                (ec_add_input_x2_limb_5.clone() - ec_add_input_x1_limb_5.clone()),
                (ec_add_input_x2_limb_6.clone() - ec_add_input_x1_limb_6.clone()),
                (ec_add_input_x2_limb_7.clone() - ec_add_input_x1_limb_7.clone()),
                (ec_add_input_x2_limb_8.clone() - ec_add_input_x1_limb_8.clone()),
                (ec_add_input_x2_limb_9.clone() - ec_add_input_x1_limb_9.clone()),
                (ec_add_input_x2_limb_10.clone() - ec_add_input_x1_limb_10.clone()),
                (ec_add_input_x2_limb_11.clone() - ec_add_input_x1_limb_11.clone()),
                (ec_add_input_x2_limb_12.clone() - ec_add_input_x1_limb_12.clone()),
                (ec_add_input_x2_limb_13.clone() - ec_add_input_x1_limb_13.clone()),
                (ec_add_input_x2_limb_14.clone() - ec_add_input_x1_limb_14.clone()),
                (ec_add_input_x2_limb_15.clone() - ec_add_input_x1_limb_15.clone()),
                (ec_add_input_x2_limb_16.clone() - ec_add_input_x1_limb_16.clone()),
                (ec_add_input_x2_limb_17.clone() - ec_add_input_x1_limb_17.clone()),
                (ec_add_input_x2_limb_18.clone() - ec_add_input_x1_limb_18.clone()),
                (ec_add_input_x2_limb_19.clone() - ec_add_input_x1_limb_19.clone()),
                (ec_add_input_x2_limb_20.clone() - ec_add_input_x1_limb_20.clone()),
                (ec_add_input_x2_limb_21.clone() - ec_add_input_x1_limb_21.clone()),
                (ec_add_input_x2_limb_22.clone() - ec_add_input_x1_limb_22.clone()),
                (ec_add_input_x2_limb_23.clone() - ec_add_input_x1_limb_23.clone()),
                (ec_add_input_x2_limb_24.clone() - ec_add_input_x1_limb_24.clone()),
                (ec_add_input_x2_limb_25.clone() - ec_add_input_x1_limb_25.clone()),
                (ec_add_input_x2_limb_26.clone() - ec_add_input_x1_limb_26.clone()),
                (ec_add_input_x2_limb_27.clone() - ec_add_input_x1_limb_27.clone()),
                (ec_add_input_y2_limb_0.clone() - ec_add_input_y1_limb_0.clone()),
                (ec_add_input_y2_limb_1.clone() - ec_add_input_y1_limb_1.clone()),
                (ec_add_input_y2_limb_2.clone() - ec_add_input_y1_limb_2.clone()),
                (ec_add_input_y2_limb_3.clone() - ec_add_input_y1_limb_3.clone()),
                (ec_add_input_y2_limb_4.clone() - ec_add_input_y1_limb_4.clone()),
                (ec_add_input_y2_limb_5.clone() - ec_add_input_y1_limb_5.clone()),
                (ec_add_input_y2_limb_6.clone() - ec_add_input_y1_limb_6.clone()),
                (ec_add_input_y2_limb_7.clone() - ec_add_input_y1_limb_7.clone()),
                (ec_add_input_y2_limb_8.clone() - ec_add_input_y1_limb_8.clone()),
                (ec_add_input_y2_limb_9.clone() - ec_add_input_y1_limb_9.clone()),
                (ec_add_input_y2_limb_10.clone() - ec_add_input_y1_limb_10.clone()),
                (ec_add_input_y2_limb_11.clone() - ec_add_input_y1_limb_11.clone()),
                (ec_add_input_y2_limb_12.clone() - ec_add_input_y1_limb_12.clone()),
                (ec_add_input_y2_limb_13.clone() - ec_add_input_y1_limb_13.clone()),
                (ec_add_input_y2_limb_14.clone() - ec_add_input_y1_limb_14.clone()),
                (ec_add_input_y2_limb_15.clone() - ec_add_input_y1_limb_15.clone()),
                (ec_add_input_y2_limb_16.clone() - ec_add_input_y1_limb_16.clone()),
                (ec_add_input_y2_limb_17.clone() - ec_add_input_y1_limb_17.clone()),
                (ec_add_input_y2_limb_18.clone() - ec_add_input_y1_limb_18.clone()),
                (ec_add_input_y2_limb_19.clone() - ec_add_input_y1_limb_19.clone()),
                (ec_add_input_y2_limb_20.clone() - ec_add_input_y1_limb_20.clone()),
                (ec_add_input_y2_limb_21.clone() - ec_add_input_y1_limb_21.clone()),
                (ec_add_input_y2_limb_22.clone() - ec_add_input_y1_limb_22.clone()),
                (ec_add_input_y2_limb_23.clone() - ec_add_input_y1_limb_23.clone()),
                (ec_add_input_y2_limb_24.clone() - ec_add_input_y1_limb_24.clone()),
                (ec_add_input_y2_limb_25.clone() - ec_add_input_y1_limb_25.clone()),
                (ec_add_input_y2_limb_26.clone() - ec_add_input_y1_limb_26.clone()),
                (ec_add_input_y2_limb_27.clone() - ec_add_input_y1_limb_27.clone()),
            ],
            k_col28.clone(),
            carry_0_col29.clone(),
            carry_1_col30.clone(),
            carry_2_col31.clone(),
            carry_3_col32.clone(),
            carry_4_col33.clone(),
            carry_5_col34.clone(),
            carry_6_col35.clone(),
            carry_7_col36.clone(),
            carry_8_col37.clone(),
            carry_9_col38.clone(),
            carry_10_col39.clone(),
            carry_11_col40.clone(),
            carry_12_col41.clone(),
            carry_13_col42.clone(),
            carry_14_col43.clone(),
            carry_15_col44.clone(),
            carry_16_col45.clone(),
            carry_17_col46.clone(),
            carry_18_col47.clone(),
            carry_19_col48.clone(),
            carry_20_col49.clone(),
            carry_21_col50.clone(),
            carry_22_col51.clone(),
            carry_23_col52.clone(),
            carry_24_col53.clone(),
            carry_25_col54.clone(),
            carry_26_col55.clone(),
            range_check_20_lookup_elements,
            range_check_20_b_lookup_elements,
            range_check_20_c_lookup_elements,
            range_check_20_d_lookup_elements,
            range_check_20_e_lookup_elements,
            range_check_20_f_lookup_elements,
            range_check_20_g_lookup_elements,
            range_check_20_h_lookup_elements,
            eval,
        );
        RangeCheckMemValueN28::evaluate(
            [
                result_x_limb_0_col56.clone(),
                result_x_limb_1_col57.clone(),
                result_x_limb_2_col58.clone(),
                result_x_limb_3_col59.clone(),
                result_x_limb_4_col60.clone(),
                result_x_limb_5_col61.clone(),
                result_x_limb_6_col62.clone(),
                result_x_limb_7_col63.clone(),
                result_x_limb_8_col64.clone(),
                result_x_limb_9_col65.clone(),
                result_x_limb_10_col66.clone(),
                result_x_limb_11_col67.clone(),
                result_x_limb_12_col68.clone(),
                result_x_limb_13_col69.clone(),
                result_x_limb_14_col70.clone(),
                result_x_limb_15_col71.clone(),
                result_x_limb_16_col72.clone(),
                result_x_limb_17_col73.clone(),
                result_x_limb_18_col74.clone(),
                result_x_limb_19_col75.clone(),
                result_x_limb_20_col76.clone(),
                result_x_limb_21_col77.clone(),
                result_x_limb_22_col78.clone(),
                result_x_limb_23_col79.clone(),
                result_x_limb_24_col80.clone(),
                result_x_limb_25_col81.clone(),
                result_x_limb_26_col82.clone(),
                result_x_limb_27_col83.clone(),
            ],
            range_check_9_9_lookup_elements,
            range_check_9_9_b_lookup_elements,
            range_check_9_9_c_lookup_elements,
            range_check_9_9_d_lookup_elements,
            range_check_9_9_e_lookup_elements,
            range_check_9_9_f_lookup_elements,
            range_check_9_9_g_lookup_elements,
            range_check_9_9_h_lookup_elements,
            eval,
        );
        VerifyMul252::evaluate(
            [
                slope_limb_0_col0.clone(),
                slope_limb_1_col1.clone(),
                slope_limb_2_col2.clone(),
                slope_limb_3_col3.clone(),
                slope_limb_4_col4.clone(),
                slope_limb_5_col5.clone(),
                slope_limb_6_col6.clone(),
                slope_limb_7_col7.clone(),
                slope_limb_8_col8.clone(),
                slope_limb_9_col9.clone(),
                slope_limb_10_col10.clone(),
                slope_limb_11_col11.clone(),
                slope_limb_12_col12.clone(),
                slope_limb_13_col13.clone(),
                slope_limb_14_col14.clone(),
                slope_limb_15_col15.clone(),
                slope_limb_16_col16.clone(),
                slope_limb_17_col17.clone(),
                slope_limb_18_col18.clone(),
                slope_limb_19_col19.clone(),
                slope_limb_20_col20.clone(),
                slope_limb_21_col21.clone(),
                slope_limb_22_col22.clone(),
                slope_limb_23_col23.clone(),
                slope_limb_24_col24.clone(),
                slope_limb_25_col25.clone(),
                slope_limb_26_col26.clone(),
                slope_limb_27_col27.clone(),
                slope_limb_0_col0.clone(),
                slope_limb_1_col1.clone(),
                slope_limb_2_col2.clone(),
                slope_limb_3_col3.clone(),
                slope_limb_4_col4.clone(),
                slope_limb_5_col5.clone(),
                slope_limb_6_col6.clone(),
                slope_limb_7_col7.clone(),
                slope_limb_8_col8.clone(),
                slope_limb_9_col9.clone(),
                slope_limb_10_col10.clone(),
                slope_limb_11_col11.clone(),
                slope_limb_12_col12.clone(),
                slope_limb_13_col13.clone(),
                slope_limb_14_col14.clone(),
                slope_limb_15_col15.clone(),
                slope_limb_16_col16.clone(),
                slope_limb_17_col17.clone(),
                slope_limb_18_col18.clone(),
                slope_limb_19_col19.clone(),
                slope_limb_20_col20.clone(),
                slope_limb_21_col21.clone(),
                slope_limb_22_col22.clone(),
                slope_limb_23_col23.clone(),
                slope_limb_24_col24.clone(),
                slope_limb_25_col25.clone(),
                slope_limb_26_col26.clone(),
                slope_limb_27_col27.clone(),
                ((ec_add_input_x1_limb_0.clone() + ec_add_input_x2_limb_0.clone())
                    + result_x_limb_0_col56.clone()),
                ((ec_add_input_x1_limb_1.clone() + ec_add_input_x2_limb_1.clone())
                    + result_x_limb_1_col57.clone()),
                ((ec_add_input_x1_limb_2.clone() + ec_add_input_x2_limb_2.clone())
                    + result_x_limb_2_col58.clone()),
                ((ec_add_input_x1_limb_3.clone() + ec_add_input_x2_limb_3.clone())
                    + result_x_limb_3_col59.clone()),
                ((ec_add_input_x1_limb_4.clone() + ec_add_input_x2_limb_4.clone())
                    + result_x_limb_4_col60.clone()),
                ((ec_add_input_x1_limb_5.clone() + ec_add_input_x2_limb_5.clone())
                    + result_x_limb_5_col61.clone()),
                ((ec_add_input_x1_limb_6.clone() + ec_add_input_x2_limb_6.clone())
                    + result_x_limb_6_col62.clone()),
                ((ec_add_input_x1_limb_7.clone() + ec_add_input_x2_limb_7.clone())
                    + result_x_limb_7_col63.clone()),
                ((ec_add_input_x1_limb_8.clone() + ec_add_input_x2_limb_8.clone())
                    + result_x_limb_8_col64.clone()),
                ((ec_add_input_x1_limb_9.clone() + ec_add_input_x2_limb_9.clone())
                    + result_x_limb_9_col65.clone()),
                ((ec_add_input_x1_limb_10.clone() + ec_add_input_x2_limb_10.clone())
                    + result_x_limb_10_col66.clone()),
                ((ec_add_input_x1_limb_11.clone() + ec_add_input_x2_limb_11.clone())
                    + result_x_limb_11_col67.clone()),
                ((ec_add_input_x1_limb_12.clone() + ec_add_input_x2_limb_12.clone())
                    + result_x_limb_12_col68.clone()),
                ((ec_add_input_x1_limb_13.clone() + ec_add_input_x2_limb_13.clone())
                    + result_x_limb_13_col69.clone()),
                ((ec_add_input_x1_limb_14.clone() + ec_add_input_x2_limb_14.clone())
                    + result_x_limb_14_col70.clone()),
                ((ec_add_input_x1_limb_15.clone() + ec_add_input_x2_limb_15.clone())
                    + result_x_limb_15_col71.clone()),
                ((ec_add_input_x1_limb_16.clone() + ec_add_input_x2_limb_16.clone())
                    + result_x_limb_16_col72.clone()),
                ((ec_add_input_x1_limb_17.clone() + ec_add_input_x2_limb_17.clone())
                    + result_x_limb_17_col73.clone()),
                ((ec_add_input_x1_limb_18.clone() + ec_add_input_x2_limb_18.clone())
                    + result_x_limb_18_col74.clone()),
                ((ec_add_input_x1_limb_19.clone() + ec_add_input_x2_limb_19.clone())
                    + result_x_limb_19_col75.clone()),
                ((ec_add_input_x1_limb_20.clone() + ec_add_input_x2_limb_20.clone())
                    + result_x_limb_20_col76.clone()),
                ((ec_add_input_x1_limb_21.clone() + ec_add_input_x2_limb_21.clone())
                    + result_x_limb_21_col77.clone()),
                ((ec_add_input_x1_limb_22.clone() + ec_add_input_x2_limb_22.clone())
                    + result_x_limb_22_col78.clone()),
                ((ec_add_input_x1_limb_23.clone() + ec_add_input_x2_limb_23.clone())
                    + result_x_limb_23_col79.clone()),
                ((ec_add_input_x1_limb_24.clone() + ec_add_input_x2_limb_24.clone())
                    + result_x_limb_24_col80.clone()),
                ((ec_add_input_x1_limb_25.clone() + ec_add_input_x2_limb_25.clone())
                    + result_x_limb_25_col81.clone()),
                ((ec_add_input_x1_limb_26.clone() + ec_add_input_x2_limb_26.clone())
                    + result_x_limb_26_col82.clone()),
                ((ec_add_input_x1_limb_27.clone() + ec_add_input_x2_limb_27.clone())
                    + result_x_limb_27_col83.clone()),
            ],
            k_col84.clone(),
            carry_0_col85.clone(),
            carry_1_col86.clone(),
            carry_2_col87.clone(),
            carry_3_col88.clone(),
            carry_4_col89.clone(),
            carry_5_col90.clone(),
            carry_6_col91.clone(),
            carry_7_col92.clone(),
            carry_8_col93.clone(),
            carry_9_col94.clone(),
            carry_10_col95.clone(),
            carry_11_col96.clone(),
            carry_12_col97.clone(),
            carry_13_col98.clone(),
            carry_14_col99.clone(),
            carry_15_col100.clone(),
            carry_16_col101.clone(),
            carry_17_col102.clone(),
            carry_18_col103.clone(),
            carry_19_col104.clone(),
            carry_20_col105.clone(),
            carry_21_col106.clone(),
            carry_22_col107.clone(),
            carry_23_col108.clone(),
            carry_24_col109.clone(),
            carry_25_col110.clone(),
            carry_26_col111.clone(),
            range_check_20_lookup_elements,
            range_check_20_b_lookup_elements,
            range_check_20_c_lookup_elements,
            range_check_20_d_lookup_elements,
            range_check_20_e_lookup_elements,
            range_check_20_f_lookup_elements,
            range_check_20_g_lookup_elements,
            range_check_20_h_lookup_elements,
            eval,
        );
        RangeCheckMemValueN28::evaluate(
            [
                result_y_limb_0_col112.clone(),
                result_y_limb_1_col113.clone(),
                result_y_limb_2_col114.clone(),
                result_y_limb_3_col115.clone(),
                result_y_limb_4_col116.clone(),
                result_y_limb_5_col117.clone(),
                result_y_limb_6_col118.clone(),
                result_y_limb_7_col119.clone(),
                result_y_limb_8_col120.clone(),
                result_y_limb_9_col121.clone(),
                result_y_limb_10_col122.clone(),
                result_y_limb_11_col123.clone(),
                result_y_limb_12_col124.clone(),
                result_y_limb_13_col125.clone(),
                result_y_limb_14_col126.clone(),
                result_y_limb_15_col127.clone(),
                result_y_limb_16_col128.clone(),
                result_y_limb_17_col129.clone(),
                result_y_limb_18_col130.clone(),
                result_y_limb_19_col131.clone(),
                result_y_limb_20_col132.clone(),
                result_y_limb_21_col133.clone(),
                result_y_limb_22_col134.clone(),
                result_y_limb_23_col135.clone(),
                result_y_limb_24_col136.clone(),
                result_y_limb_25_col137.clone(),
                result_y_limb_26_col138.clone(),
                result_y_limb_27_col139.clone(),
            ],
            range_check_9_9_lookup_elements,
            range_check_9_9_b_lookup_elements,
            range_check_9_9_c_lookup_elements,
            range_check_9_9_d_lookup_elements,
            range_check_9_9_e_lookup_elements,
            range_check_9_9_f_lookup_elements,
            range_check_9_9_g_lookup_elements,
            range_check_9_9_h_lookup_elements,
            eval,
        );
        VerifyMul252::evaluate(
            [
                slope_limb_0_col0.clone(),
                slope_limb_1_col1.clone(),
                slope_limb_2_col2.clone(),
                slope_limb_3_col3.clone(),
                slope_limb_4_col4.clone(),
                slope_limb_5_col5.clone(),
                slope_limb_6_col6.clone(),
                slope_limb_7_col7.clone(),
                slope_limb_8_col8.clone(),
                slope_limb_9_col9.clone(),
                slope_limb_10_col10.clone(),
                slope_limb_11_col11.clone(),
                slope_limb_12_col12.clone(),
                slope_limb_13_col13.clone(),
                slope_limb_14_col14.clone(),
                slope_limb_15_col15.clone(),
                slope_limb_16_col16.clone(),
                slope_limb_17_col17.clone(),
                slope_limb_18_col18.clone(),
                slope_limb_19_col19.clone(),
                slope_limb_20_col20.clone(),
                slope_limb_21_col21.clone(),
                slope_limb_22_col22.clone(),
                slope_limb_23_col23.clone(),
                slope_limb_24_col24.clone(),
                slope_limb_25_col25.clone(),
                slope_limb_26_col26.clone(),
                slope_limb_27_col27.clone(),
                (ec_add_input_x1_limb_0.clone() - result_x_limb_0_col56.clone()),
                (ec_add_input_x1_limb_1.clone() - result_x_limb_1_col57.clone()),
                (ec_add_input_x1_limb_2.clone() - result_x_limb_2_col58.clone()),
                (ec_add_input_x1_limb_3.clone() - result_x_limb_3_col59.clone()),
                (ec_add_input_x1_limb_4.clone() - result_x_limb_4_col60.clone()),
                (ec_add_input_x1_limb_5.clone() - result_x_limb_5_col61.clone()),
                (ec_add_input_x1_limb_6.clone() - result_x_limb_6_col62.clone()),
                (ec_add_input_x1_limb_7.clone() - result_x_limb_7_col63.clone()),
                (ec_add_input_x1_limb_8.clone() - result_x_limb_8_col64.clone()),
                (ec_add_input_x1_limb_9.clone() - result_x_limb_9_col65.clone()),
                (ec_add_input_x1_limb_10.clone() - result_x_limb_10_col66.clone()),
                (ec_add_input_x1_limb_11.clone() - result_x_limb_11_col67.clone()),
                (ec_add_input_x1_limb_12.clone() - result_x_limb_12_col68.clone()),
                (ec_add_input_x1_limb_13.clone() - result_x_limb_13_col69.clone()),
                (ec_add_input_x1_limb_14.clone() - result_x_limb_14_col70.clone()),
                (ec_add_input_x1_limb_15.clone() - result_x_limb_15_col71.clone()),
                (ec_add_input_x1_limb_16.clone() - result_x_limb_16_col72.clone()),
                (ec_add_input_x1_limb_17.clone() - result_x_limb_17_col73.clone()),
                (ec_add_input_x1_limb_18.clone() - result_x_limb_18_col74.clone()),
                (ec_add_input_x1_limb_19.clone() - result_x_limb_19_col75.clone()),
                (ec_add_input_x1_limb_20.clone() - result_x_limb_20_col76.clone()),
                (ec_add_input_x1_limb_21.clone() - result_x_limb_21_col77.clone()),
                (ec_add_input_x1_limb_22.clone() - result_x_limb_22_col78.clone()),
                (ec_add_input_x1_limb_23.clone() - result_x_limb_23_col79.clone()),
                (ec_add_input_x1_limb_24.clone() - result_x_limb_24_col80.clone()),
                (ec_add_input_x1_limb_25.clone() - result_x_limb_25_col81.clone()),
                (ec_add_input_x1_limb_26.clone() - result_x_limb_26_col82.clone()),
                (ec_add_input_x1_limb_27.clone() - result_x_limb_27_col83.clone()),
                (ec_add_input_y1_limb_0.clone() + result_y_limb_0_col112.clone()),
                (ec_add_input_y1_limb_1.clone() + result_y_limb_1_col113.clone()),
                (ec_add_input_y1_limb_2.clone() + result_y_limb_2_col114.clone()),
                (ec_add_input_y1_limb_3.clone() + result_y_limb_3_col115.clone()),
                (ec_add_input_y1_limb_4.clone() + result_y_limb_4_col116.clone()),
                (ec_add_input_y1_limb_5.clone() + result_y_limb_5_col117.clone()),
                (ec_add_input_y1_limb_6.clone() + result_y_limb_6_col118.clone()),
                (ec_add_input_y1_limb_7.clone() + result_y_limb_7_col119.clone()),
                (ec_add_input_y1_limb_8.clone() + result_y_limb_8_col120.clone()),
                (ec_add_input_y1_limb_9.clone() + result_y_limb_9_col121.clone()),
                (ec_add_input_y1_limb_10.clone() + result_y_limb_10_col122.clone()),
                (ec_add_input_y1_limb_11.clone() + result_y_limb_11_col123.clone()),
                (ec_add_input_y1_limb_12.clone() + result_y_limb_12_col124.clone()),
                (ec_add_input_y1_limb_13.clone() + result_y_limb_13_col125.clone()),
                (ec_add_input_y1_limb_14.clone() + result_y_limb_14_col126.clone()),
                (ec_add_input_y1_limb_15.clone() + result_y_limb_15_col127.clone()),
                (ec_add_input_y1_limb_16.clone() + result_y_limb_16_col128.clone()),
                (ec_add_input_y1_limb_17.clone() + result_y_limb_17_col129.clone()),
                (ec_add_input_y1_limb_18.clone() + result_y_limb_18_col130.clone()),
                (ec_add_input_y1_limb_19.clone() + result_y_limb_19_col131.clone()),
                (ec_add_input_y1_limb_20.clone() + result_y_limb_20_col132.clone()),
                (ec_add_input_y1_limb_21.clone() + result_y_limb_21_col133.clone()),
                (ec_add_input_y1_limb_22.clone() + result_y_limb_22_col134.clone()),
                (ec_add_input_y1_limb_23.clone() + result_y_limb_23_col135.clone()),
                (ec_add_input_y1_limb_24.clone() + result_y_limb_24_col136.clone()),
                (ec_add_input_y1_limb_25.clone() + result_y_limb_25_col137.clone()),
                (ec_add_input_y1_limb_26.clone() + result_y_limb_26_col138.clone()),
                (ec_add_input_y1_limb_27.clone() + result_y_limb_27_col139.clone()),
            ],
            k_col140.clone(),
            carry_0_col141.clone(),
            carry_1_col142.clone(),
            carry_2_col143.clone(),
            carry_3_col144.clone(),
            carry_4_col145.clone(),
            carry_5_col146.clone(),
            carry_6_col147.clone(),
            carry_7_col148.clone(),
            carry_8_col149.clone(),
            carry_9_col150.clone(),
            carry_10_col151.clone(),
            carry_11_col152.clone(),
            carry_12_col153.clone(),
            carry_13_col154.clone(),
            carry_14_col155.clone(),
            carry_15_col156.clone(),
            carry_16_col157.clone(),
            carry_17_col158.clone(),
            carry_18_col159.clone(),
            carry_19_col160.clone(),
            carry_20_col161.clone(),
            carry_21_col162.clone(),
            carry_22_col163.clone(),
            carry_23_col164.clone(),
            carry_24_col165.clone(),
            carry_25_col166.clone(),
            carry_26_col167.clone(),
            range_check_20_lookup_elements,
            range_check_20_b_lookup_elements,
            range_check_20_c_lookup_elements,
            range_check_20_d_lookup_elements,
            range_check_20_e_lookup_elements,
            range_check_20_f_lookup_elements,
            range_check_20_g_lookup_elements,
            range_check_20_h_lookup_elements,
            eval,
        );
        []
    }
}
