use crate::components::prelude::*;
use crate::components::subroutines::mem_cond_verify_equal_known_id::MemCondVerifyEqualKnownId;
use crate::components::subroutines::read_positive_num_bits_27::ReadPositiveNumBits27;
use crate::components::subroutines::read_positive_num_bits_99::ReadPositiveNumBits99;
use crate::components::subroutines::read_small::ReadSmall;

#[derive(Copy, Clone, Serialize, Deserialize, CairoSerialize)]
pub struct ModUtils {}

impl ModUtils {
    #[allow(unused_parens)]
    #[allow(clippy::double_parens)]
    #[allow(non_snake_case)]
    #[allow(clippy::unused_unit)]
    #[allow(unused_variables)]
    #[allow(clippy::too_many_arguments)]
    pub fn evaluate<E: EvalAtRow>(
        segment_index: E::F,
        mod_utils_input_limb_1: E::F,
        is_instance_0_col0: E::F,
        p0_id_col1: E::F,
        p0_limb_0_col2: E::F,
        p0_limb_1_col3: E::F,
        p0_limb_2_col4: E::F,
        p0_limb_3_col5: E::F,
        p0_limb_4_col6: E::F,
        p0_limb_5_col7: E::F,
        p0_limb_6_col8: E::F,
        p0_limb_7_col9: E::F,
        p0_limb_8_col10: E::F,
        p0_limb_9_col11: E::F,
        p0_limb_10_col12: E::F,
        p1_id_col13: E::F,
        p1_limb_0_col14: E::F,
        p1_limb_1_col15: E::F,
        p1_limb_2_col16: E::F,
        p1_limb_3_col17: E::F,
        p1_limb_4_col18: E::F,
        p1_limb_5_col19: E::F,
        p1_limb_6_col20: E::F,
        p1_limb_7_col21: E::F,
        p1_limb_8_col22: E::F,
        p1_limb_9_col23: E::F,
        p1_limb_10_col24: E::F,
        p2_id_col25: E::F,
        p2_limb_0_col26: E::F,
        p2_limb_1_col27: E::F,
        p2_limb_2_col28: E::F,
        p2_limb_3_col29: E::F,
        p2_limb_4_col30: E::F,
        p2_limb_5_col31: E::F,
        p2_limb_6_col32: E::F,
        p2_limb_7_col33: E::F,
        p2_limb_8_col34: E::F,
        p2_limb_9_col35: E::F,
        p2_limb_10_col36: E::F,
        p3_id_col37: E::F,
        p3_limb_0_col38: E::F,
        p3_limb_1_col39: E::F,
        p3_limb_2_col40: E::F,
        p3_limb_3_col41: E::F,
        p3_limb_4_col42: E::F,
        p3_limb_5_col43: E::F,
        p3_limb_6_col44: E::F,
        p3_limb_7_col45: E::F,
        p3_limb_8_col46: E::F,
        p3_limb_9_col47: E::F,
        p3_limb_10_col48: E::F,
        values_ptr_id_col49: E::F,
        values_ptr_limb_0_col50: E::F,
        values_ptr_limb_1_col51: E::F,
        values_ptr_limb_2_col52: E::F,
        offsets_ptr_id_col53: E::F,
        offsets_ptr_limb_0_col54: E::F,
        offsets_ptr_limb_1_col55: E::F,
        offsets_ptr_limb_2_col56: E::F,
        offsets_ptr_prev_id_col57: E::F,
        offsets_ptr_prev_limb_0_col58: E::F,
        offsets_ptr_prev_limb_1_col59: E::F,
        offsets_ptr_prev_limb_2_col60: E::F,
        n_id_col61: E::F,
        n_limb_0_col62: E::F,
        n_limb_1_col63: E::F,
        n_limb_2_col64: E::F,
        n_prev_id_col65: E::F,
        n_prev_limb_0_col66: E::F,
        n_prev_limb_1_col67: E::F,
        n_prev_limb_2_col68: E::F,
        values_ptr_prev_id_col69: E::F,
        p_prev0_id_col70: E::F,
        p_prev1_id_col71: E::F,
        p_prev2_id_col72: E::F,
        p_prev3_id_col73: E::F,
        offsets_a_id_col74: E::F,
        msb_col75: E::F,
        mid_limbs_set_col76: E::F,
        offsets_a_limb_0_col77: E::F,
        offsets_a_limb_1_col78: E::F,
        offsets_a_limb_2_col79: E::F,
        offsets_b_id_col80: E::F,
        msb_col81: E::F,
        mid_limbs_set_col82: E::F,
        offsets_b_limb_0_col83: E::F,
        offsets_b_limb_1_col84: E::F,
        offsets_b_limb_2_col85: E::F,
        offsets_c_id_col86: E::F,
        msb_col87: E::F,
        mid_limbs_set_col88: E::F,
        offsets_c_limb_0_col89: E::F,
        offsets_c_limb_1_col90: E::F,
        offsets_c_limb_2_col91: E::F,
        a0_id_col92: E::F,
        a0_limb_0_col93: E::F,
        a0_limb_1_col94: E::F,
        a0_limb_2_col95: E::F,
        a0_limb_3_col96: E::F,
        a0_limb_4_col97: E::F,
        a0_limb_5_col98: E::F,
        a0_limb_6_col99: E::F,
        a0_limb_7_col100: E::F,
        a0_limb_8_col101: E::F,
        a0_limb_9_col102: E::F,
        a0_limb_10_col103: E::F,
        a1_id_col104: E::F,
        a1_limb_0_col105: E::F,
        a1_limb_1_col106: E::F,
        a1_limb_2_col107: E::F,
        a1_limb_3_col108: E::F,
        a1_limb_4_col109: E::F,
        a1_limb_5_col110: E::F,
        a1_limb_6_col111: E::F,
        a1_limb_7_col112: E::F,
        a1_limb_8_col113: E::F,
        a1_limb_9_col114: E::F,
        a1_limb_10_col115: E::F,
        a2_id_col116: E::F,
        a2_limb_0_col117: E::F,
        a2_limb_1_col118: E::F,
        a2_limb_2_col119: E::F,
        a2_limb_3_col120: E::F,
        a2_limb_4_col121: E::F,
        a2_limb_5_col122: E::F,
        a2_limb_6_col123: E::F,
        a2_limb_7_col124: E::F,
        a2_limb_8_col125: E::F,
        a2_limb_9_col126: E::F,
        a2_limb_10_col127: E::F,
        a3_id_col128: E::F,
        a3_limb_0_col129: E::F,
        a3_limb_1_col130: E::F,
        a3_limb_2_col131: E::F,
        a3_limb_3_col132: E::F,
        a3_limb_4_col133: E::F,
        a3_limb_5_col134: E::F,
        a3_limb_6_col135: E::F,
        a3_limb_7_col136: E::F,
        a3_limb_8_col137: E::F,
        a3_limb_9_col138: E::F,
        a3_limb_10_col139: E::F,
        b0_id_col140: E::F,
        b0_limb_0_col141: E::F,
        b0_limb_1_col142: E::F,
        b0_limb_2_col143: E::F,
        b0_limb_3_col144: E::F,
        b0_limb_4_col145: E::F,
        b0_limb_5_col146: E::F,
        b0_limb_6_col147: E::F,
        b0_limb_7_col148: E::F,
        b0_limb_8_col149: E::F,
        b0_limb_9_col150: E::F,
        b0_limb_10_col151: E::F,
        b1_id_col152: E::F,
        b1_limb_0_col153: E::F,
        b1_limb_1_col154: E::F,
        b1_limb_2_col155: E::F,
        b1_limb_3_col156: E::F,
        b1_limb_4_col157: E::F,
        b1_limb_5_col158: E::F,
        b1_limb_6_col159: E::F,
        b1_limb_7_col160: E::F,
        b1_limb_8_col161: E::F,
        b1_limb_9_col162: E::F,
        b1_limb_10_col163: E::F,
        b2_id_col164: E::F,
        b2_limb_0_col165: E::F,
        b2_limb_1_col166: E::F,
        b2_limb_2_col167: E::F,
        b2_limb_3_col168: E::F,
        b2_limb_4_col169: E::F,
        b2_limb_5_col170: E::F,
        b2_limb_6_col171: E::F,
        b2_limb_7_col172: E::F,
        b2_limb_8_col173: E::F,
        b2_limb_9_col174: E::F,
        b2_limb_10_col175: E::F,
        b3_id_col176: E::F,
        b3_limb_0_col177: E::F,
        b3_limb_1_col178: E::F,
        b3_limb_2_col179: E::F,
        b3_limb_3_col180: E::F,
        b3_limb_4_col181: E::F,
        b3_limb_5_col182: E::F,
        b3_limb_6_col183: E::F,
        b3_limb_7_col184: E::F,
        b3_limb_8_col185: E::F,
        b3_limb_9_col186: E::F,
        b3_limb_10_col187: E::F,
        c0_id_col188: E::F,
        c0_limb_0_col189: E::F,
        c0_limb_1_col190: E::F,
        c0_limb_2_col191: E::F,
        c0_limb_3_col192: E::F,
        c0_limb_4_col193: E::F,
        c0_limb_5_col194: E::F,
        c0_limb_6_col195: E::F,
        c0_limb_7_col196: E::F,
        c0_limb_8_col197: E::F,
        c0_limb_9_col198: E::F,
        c0_limb_10_col199: E::F,
        c1_id_col200: E::F,
        c1_limb_0_col201: E::F,
        c1_limb_1_col202: E::F,
        c1_limb_2_col203: E::F,
        c1_limb_3_col204: E::F,
        c1_limb_4_col205: E::F,
        c1_limb_5_col206: E::F,
        c1_limb_6_col207: E::F,
        c1_limb_7_col208: E::F,
        c1_limb_8_col209: E::F,
        c1_limb_9_col210: E::F,
        c1_limb_10_col211: E::F,
        c2_id_col212: E::F,
        c2_limb_0_col213: E::F,
        c2_limb_1_col214: E::F,
        c2_limb_2_col215: E::F,
        c2_limb_3_col216: E::F,
        c2_limb_4_col217: E::F,
        c2_limb_5_col218: E::F,
        c2_limb_6_col219: E::F,
        c2_limb_7_col220: E::F,
        c2_limb_8_col221: E::F,
        c2_limb_9_col222: E::F,
        c2_limb_10_col223: E::F,
        c3_id_col224: E::F,
        c3_limb_0_col225: E::F,
        c3_limb_1_col226: E::F,
        c3_limb_2_col227: E::F,
        c3_limb_3_col228: E::F,
        c3_limb_4_col229: E::F,
        c3_limb_5_col230: E::F,
        c3_limb_6_col231: E::F,
        c3_limb_7_col232: E::F,
        c3_limb_8_col233: E::F,
        c3_limb_9_col234: E::F,
        c3_limb_10_col235: E::F,
        memory_address_to_id_lookup_elements: &relations::MemoryAddressToId,
        memory_id_to_big_lookup_elements: &relations::MemoryIdToBig,
        eval: &mut E,
    ) -> [E::F; 0] {
        let M31_1 = E::F::from(M31::from(1));
        let M31_2 = E::F::from(M31::from(2));
        let M31_262144 = E::F::from(M31::from(262144));
        let M31_3 = E::F::from(M31::from(3));
        let M31_4 = E::F::from(M31::from(4));
        let M31_5 = E::F::from(M31::from(5));
        let M31_512 = E::F::from(M31::from(512));
        let M31_6 = E::F::from(M31::from(6));
        let M31_7 = E::F::from(M31::from(7));

        // is_instance_0 is 0 or 1..
        eval.add_constraint(
            (is_instance_0_col0.clone() * (is_instance_0_col0.clone() - M31_1.clone())),
        );
        // is_instance_0 is 0 when instance_num is not 0..
        eval.add_constraint((is_instance_0_col0.clone() * mod_utils_input_limb_1.clone()));
        let prev_instance_addr_tmp_7b599_1 = eval.add_intermediate(
            (M31_7.clone()
                * ((mod_utils_input_limb_1.clone() - M31_1.clone()) + is_instance_0_col0.clone())),
        );
        let instance_addr_tmp_7b599_2 =
            eval.add_intermediate((M31_7.clone() * mod_utils_input_limb_1.clone()));
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [instance_addr_tmp_7b599_2.clone()],
            p0_id_col1.clone(),
            p0_limb_0_col2.clone(),
            p0_limb_1_col3.clone(),
            p0_limb_2_col4.clone(),
            p0_limb_3_col5.clone(),
            p0_limb_4_col6.clone(),
            p0_limb_5_col7.clone(),
            p0_limb_6_col8.clone(),
            p0_limb_7_col9.clone(),
            p0_limb_8_col10.clone(),
            p0_limb_9_col11.clone(),
            p0_limb_10_col12.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [(instance_addr_tmp_7b599_2.clone() + M31_1.clone())],
            p1_id_col13.clone(),
            p1_limb_0_col14.clone(),
            p1_limb_1_col15.clone(),
            p1_limb_2_col16.clone(),
            p1_limb_3_col17.clone(),
            p1_limb_4_col18.clone(),
            p1_limb_5_col19.clone(),
            p1_limb_6_col20.clone(),
            p1_limb_7_col21.clone(),
            p1_limb_8_col22.clone(),
            p1_limb_9_col23.clone(),
            p1_limb_10_col24.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [(instance_addr_tmp_7b599_2.clone() + M31_2.clone())],
            p2_id_col25.clone(),
            p2_limb_0_col26.clone(),
            p2_limb_1_col27.clone(),
            p2_limb_2_col28.clone(),
            p2_limb_3_col29.clone(),
            p2_limb_4_col30.clone(),
            p2_limb_5_col31.clone(),
            p2_limb_6_col32.clone(),
            p2_limb_7_col33.clone(),
            p2_limb_8_col34.clone(),
            p2_limb_9_col35.clone(),
            p2_limb_10_col36.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [(instance_addr_tmp_7b599_2.clone() + M31_3.clone())],
            p3_id_col37.clone(),
            p3_limb_0_col38.clone(),
            p3_limb_1_col39.clone(),
            p3_limb_2_col40.clone(),
            p3_limb_3_col41.clone(),
            p3_limb_4_col42.clone(),
            p3_limb_5_col43.clone(),
            p3_limb_6_col44.clone(),
            p3_limb_7_col45.clone(),
            p3_limb_8_col46.clone(),
            p3_limb_9_col47.clone(),
            p3_limb_10_col48.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits27::evaluate(
            segment_index.clone(),
            [(instance_addr_tmp_7b599_2.clone() + M31_4.clone())],
            values_ptr_id_col49.clone(),
            values_ptr_limb_0_col50.clone(),
            values_ptr_limb_1_col51.clone(),
            values_ptr_limb_2_col52.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits27::evaluate(
            segment_index.clone(),
            [(instance_addr_tmp_7b599_2.clone() + M31_5.clone())],
            offsets_ptr_id_col53.clone(),
            offsets_ptr_limb_0_col54.clone(),
            offsets_ptr_limb_1_col55.clone(),
            offsets_ptr_limb_2_col56.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits27::evaluate(
            segment_index.clone(),
            [(prev_instance_addr_tmp_7b599_1.clone() + M31_5.clone())],
            offsets_ptr_prev_id_col57.clone(),
            offsets_ptr_prev_limb_0_col58.clone(),
            offsets_ptr_prev_limb_1_col59.clone(),
            offsets_ptr_prev_limb_2_col60.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits27::evaluate(
            segment_index.clone(),
            [(instance_addr_tmp_7b599_2.clone() + M31_6.clone())],
            n_id_col61.clone(),
            n_limb_0_col62.clone(),
            n_limb_1_col63.clone(),
            n_limb_2_col64.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits27::evaluate(
            segment_index.clone(),
            [(prev_instance_addr_tmp_7b599_1.clone() + M31_6.clone())],
            n_prev_id_col65.clone(),
            n_prev_limb_0_col66.clone(),
            n_prev_limb_1_col67.clone(),
            n_prev_limb_2_col68.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        let block_reset_condition_tmp_7b599_30 = eval.add_intermediate(
            ((((n_prev_limb_0_col66.clone() + (n_prev_limb_1_col67.clone() * M31_512.clone()))
                + (n_prev_limb_2_col68.clone() * M31_262144.clone()))
                - M31_1.clone())
                * (is_instance_0_col0.clone() - M31_1.clone())),
        );
        // Progression of n between instances..
        eval.add_constraint(
            (block_reset_condition_tmp_7b599_30.clone()
                * ((((n_prev_limb_0_col66.clone()
                    + (n_prev_limb_1_col67.clone() * M31_512.clone()))
                    + (n_prev_limb_2_col68.clone() * M31_262144.clone()))
                    - M31_1.clone())
                    - ((n_limb_0_col62.clone() + (n_limb_1_col63.clone() * M31_512.clone()))
                        + (n_limb_2_col64.clone() * M31_262144.clone())))),
        );
        // Progression of offsets_ptr between instances..
        eval.add_constraint(
            (block_reset_condition_tmp_7b599_30.clone()
                * ((((offsets_ptr_limb_0_col54.clone()
                    + (offsets_ptr_limb_1_col55.clone() * M31_512.clone()))
                    + (offsets_ptr_limb_2_col56.clone() * M31_262144.clone()))
                    - M31_3.clone())
                    - ((offsets_ptr_prev_limb_0_col58.clone()
                        + (offsets_ptr_prev_limb_1_col59.clone() * M31_512.clone()))
                        + (offsets_ptr_prev_limb_2_col60.clone() * M31_262144.clone())))),
        );
        MemCondVerifyEqualKnownId::evaluate(
            [
                segment_index.clone(),
                (prev_instance_addr_tmp_7b599_1.clone() + M31_4.clone()),
                values_ptr_id_col49.clone(),
                block_reset_condition_tmp_7b599_30.clone(),
            ],
            values_ptr_prev_id_col69.clone(),
            memory_address_to_id_lookup_elements,
            eval,
        );
        MemCondVerifyEqualKnownId::evaluate(
            [
                segment_index.clone(),
                prev_instance_addr_tmp_7b599_1.clone(),
                p0_id_col1.clone(),
                block_reset_condition_tmp_7b599_30.clone(),
            ],
            p_prev0_id_col70.clone(),
            memory_address_to_id_lookup_elements,
            eval,
        );
        MemCondVerifyEqualKnownId::evaluate(
            [
                segment_index.clone(),
                (prev_instance_addr_tmp_7b599_1.clone() + M31_1.clone()),
                p1_id_col13.clone(),
                block_reset_condition_tmp_7b599_30.clone(),
            ],
            p_prev1_id_col71.clone(),
            memory_address_to_id_lookup_elements,
            eval,
        );
        MemCondVerifyEqualKnownId::evaluate(
            [
                segment_index.clone(),
                (prev_instance_addr_tmp_7b599_1.clone() + M31_2.clone()),
                p2_id_col25.clone(),
                block_reset_condition_tmp_7b599_30.clone(),
            ],
            p_prev2_id_col72.clone(),
            memory_address_to_id_lookup_elements,
            eval,
        );
        MemCondVerifyEqualKnownId::evaluate(
            [
                segment_index.clone(),
                (prev_instance_addr_tmp_7b599_1.clone() + M31_3.clone()),
                p3_id_col37.clone(),
                block_reset_condition_tmp_7b599_30.clone(),
            ],
            p_prev3_id_col73.clone(),
            memory_address_to_id_lookup_elements,
            eval,
        );
        let [read_small_output_tmp_7b599_41_limb_0] = ReadSmall::evaluate(
            segment_index.clone(),
            [((offsets_ptr_limb_0_col54.clone()
                + (offsets_ptr_limb_1_col55.clone() * M31_512.clone()))
                + (offsets_ptr_limb_2_col56.clone() * M31_262144.clone()))],
            offsets_a_id_col74.clone(),
            msb_col75.clone(),
            mid_limbs_set_col76.clone(),
            offsets_a_limb_0_col77.clone(),
            offsets_a_limb_1_col78.clone(),
            offsets_a_limb_2_col79.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        let [read_small_output_tmp_7b599_47_limb_0] = ReadSmall::evaluate(
            segment_index.clone(),
            [(((offsets_ptr_limb_0_col54.clone()
                + (offsets_ptr_limb_1_col55.clone() * M31_512.clone()))
                + (offsets_ptr_limb_2_col56.clone() * M31_262144.clone()))
                + M31_1.clone())],
            offsets_b_id_col80.clone(),
            msb_col81.clone(),
            mid_limbs_set_col82.clone(),
            offsets_b_limb_0_col83.clone(),
            offsets_b_limb_1_col84.clone(),
            offsets_b_limb_2_col85.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        let [read_small_output_tmp_7b599_53_limb_0] = ReadSmall::evaluate(
            segment_index.clone(),
            [(((offsets_ptr_limb_0_col54.clone()
                + (offsets_ptr_limb_1_col55.clone() * M31_512.clone()))
                + (offsets_ptr_limb_2_col56.clone() * M31_262144.clone()))
                + M31_2.clone())],
            offsets_c_id_col86.clone(),
            msb_col87.clone(),
            mid_limbs_set_col88.clone(),
            offsets_c_limb_0_col89.clone(),
            offsets_c_limb_1_col90.clone(),
            offsets_c_limb_2_col91.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        let values_ptr_tmp_7b599_54 = eval.add_intermediate(
            ((values_ptr_limb_0_col50.clone()
                + (values_ptr_limb_1_col51.clone() * M31_512.clone()))
                + (values_ptr_limb_2_col52.clone() * M31_262144.clone())),
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [(values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_41_limb_0.clone())],
            a0_id_col92.clone(),
            a0_limb_0_col93.clone(),
            a0_limb_1_col94.clone(),
            a0_limb_2_col95.clone(),
            a0_limb_3_col96.clone(),
            a0_limb_4_col97.clone(),
            a0_limb_5_col98.clone(),
            a0_limb_6_col99.clone(),
            a0_limb_7_col100.clone(),
            a0_limb_8_col101.clone(),
            a0_limb_9_col102.clone(),
            a0_limb_10_col103.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_41_limb_0.clone())
                    + M31_1.clone()),
            ],
            a1_id_col104.clone(),
            a1_limb_0_col105.clone(),
            a1_limb_1_col106.clone(),
            a1_limb_2_col107.clone(),
            a1_limb_3_col108.clone(),
            a1_limb_4_col109.clone(),
            a1_limb_5_col110.clone(),
            a1_limb_6_col111.clone(),
            a1_limb_7_col112.clone(),
            a1_limb_8_col113.clone(),
            a1_limb_9_col114.clone(),
            a1_limb_10_col115.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_41_limb_0.clone())
                    + M31_2.clone()),
            ],
            a2_id_col116.clone(),
            a2_limb_0_col117.clone(),
            a2_limb_1_col118.clone(),
            a2_limb_2_col119.clone(),
            a2_limb_3_col120.clone(),
            a2_limb_4_col121.clone(),
            a2_limb_5_col122.clone(),
            a2_limb_6_col123.clone(),
            a2_limb_7_col124.clone(),
            a2_limb_8_col125.clone(),
            a2_limb_9_col126.clone(),
            a2_limb_10_col127.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_41_limb_0.clone())
                    + M31_3.clone()),
            ],
            a3_id_col128.clone(),
            a3_limb_0_col129.clone(),
            a3_limb_1_col130.clone(),
            a3_limb_2_col131.clone(),
            a3_limb_3_col132.clone(),
            a3_limb_4_col133.clone(),
            a3_limb_5_col134.clone(),
            a3_limb_6_col135.clone(),
            a3_limb_7_col136.clone(),
            a3_limb_8_col137.clone(),
            a3_limb_9_col138.clone(),
            a3_limb_10_col139.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [(values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_47_limb_0.clone())],
            b0_id_col140.clone(),
            b0_limb_0_col141.clone(),
            b0_limb_1_col142.clone(),
            b0_limb_2_col143.clone(),
            b0_limb_3_col144.clone(),
            b0_limb_4_col145.clone(),
            b0_limb_5_col146.clone(),
            b0_limb_6_col147.clone(),
            b0_limb_7_col148.clone(),
            b0_limb_8_col149.clone(),
            b0_limb_9_col150.clone(),
            b0_limb_10_col151.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_47_limb_0.clone())
                    + M31_1.clone()),
            ],
            b1_id_col152.clone(),
            b1_limb_0_col153.clone(),
            b1_limb_1_col154.clone(),
            b1_limb_2_col155.clone(),
            b1_limb_3_col156.clone(),
            b1_limb_4_col157.clone(),
            b1_limb_5_col158.clone(),
            b1_limb_6_col159.clone(),
            b1_limb_7_col160.clone(),
            b1_limb_8_col161.clone(),
            b1_limb_9_col162.clone(),
            b1_limb_10_col163.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_47_limb_0.clone())
                    + M31_2.clone()),
            ],
            b2_id_col164.clone(),
            b2_limb_0_col165.clone(),
            b2_limb_1_col166.clone(),
            b2_limb_2_col167.clone(),
            b2_limb_3_col168.clone(),
            b2_limb_4_col169.clone(),
            b2_limb_5_col170.clone(),
            b2_limb_6_col171.clone(),
            b2_limb_7_col172.clone(),
            b2_limb_8_col173.clone(),
            b2_limb_9_col174.clone(),
            b2_limb_10_col175.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_47_limb_0.clone())
                    + M31_3.clone()),
            ],
            b3_id_col176.clone(),
            b3_limb_0_col177.clone(),
            b3_limb_1_col178.clone(),
            b3_limb_2_col179.clone(),
            b3_limb_3_col180.clone(),
            b3_limb_4_col181.clone(),
            b3_limb_5_col182.clone(),
            b3_limb_6_col183.clone(),
            b3_limb_7_col184.clone(),
            b3_limb_8_col185.clone(),
            b3_limb_9_col186.clone(),
            b3_limb_10_col187.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [(values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_53_limb_0.clone())],
            c0_id_col188.clone(),
            c0_limb_0_col189.clone(),
            c0_limb_1_col190.clone(),
            c0_limb_2_col191.clone(),
            c0_limb_3_col192.clone(),
            c0_limb_4_col193.clone(),
            c0_limb_5_col194.clone(),
            c0_limb_6_col195.clone(),
            c0_limb_7_col196.clone(),
            c0_limb_8_col197.clone(),
            c0_limb_9_col198.clone(),
            c0_limb_10_col199.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_53_limb_0.clone())
                    + M31_1.clone()),
            ],
            c1_id_col200.clone(),
            c1_limb_0_col201.clone(),
            c1_limb_1_col202.clone(),
            c1_limb_2_col203.clone(),
            c1_limb_3_col204.clone(),
            c1_limb_4_col205.clone(),
            c1_limb_5_col206.clone(),
            c1_limb_6_col207.clone(),
            c1_limb_7_col208.clone(),
            c1_limb_8_col209.clone(),
            c1_limb_9_col210.clone(),
            c1_limb_10_col211.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_53_limb_0.clone())
                    + M31_2.clone()),
            ],
            c2_id_col212.clone(),
            c2_limb_0_col213.clone(),
            c2_limb_1_col214.clone(),
            c2_limb_2_col215.clone(),
            c2_limb_3_col216.clone(),
            c2_limb_4_col217.clone(),
            c2_limb_5_col218.clone(),
            c2_limb_6_col219.clone(),
            c2_limb_7_col220.clone(),
            c2_limb_8_col221.clone(),
            c2_limb_9_col222.clone(),
            c2_limb_10_col223.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        ReadPositiveNumBits99::evaluate(
            segment_index.clone(),
            [
                ((values_ptr_tmp_7b599_54.clone() + read_small_output_tmp_7b599_53_limb_0.clone())
                    + M31_3.clone()),
            ],
            c3_id_col224.clone(),
            c3_limb_0_col225.clone(),
            c3_limb_1_col226.clone(),
            c3_limb_2_col227.clone(),
            c3_limb_3_col228.clone(),
            c3_limb_4_col229.clone(),
            c3_limb_5_col230.clone(),
            c3_limb_6_col231.clone(),
            c3_limb_7_col232.clone(),
            c3_limb_8_col233.clone(),
            c3_limb_9_col234.clone(),
            c3_limb_10_col235.clone(),
            memory_address_to_id_lookup_elements,
            memory_id_to_big_lookup_elements,
            eval,
        );
        []
    }
}
