use crate::components::prelude::*;
use crate::components::subroutines::range_check_mem_value_n_28::RangeCheckMemValueN28;
use crate::components::subroutines::verify_add_252::VerifyAdd252;

#[derive(Copy, Clone, Serialize, Deserialize, CairoSerialize)]
pub struct Sub252 {}

impl Sub252 {
    #[allow(unused_parens)]
    #[allow(clippy::double_parens)]
    #[allow(non_snake_case)]
    #[allow(clippy::unused_unit)]
    #[allow(unused_variables)]
    #[allow(clippy::too_many_arguments)]
    pub fn evaluate<E: EvalAtRow>(
        [sub_252_input_limb_0, sub_252_input_limb_1, sub_252_input_limb_2, sub_252_input_limb_3, sub_252_input_limb_4, sub_252_input_limb_5, sub_252_input_limb_6, sub_252_input_limb_7, sub_252_input_limb_8, sub_252_input_limb_9, sub_252_input_limb_10, sub_252_input_limb_11, sub_252_input_limb_12, sub_252_input_limb_13, sub_252_input_limb_14, sub_252_input_limb_15, sub_252_input_limb_16, sub_252_input_limb_17, sub_252_input_limb_18, sub_252_input_limb_19, sub_252_input_limb_20, sub_252_input_limb_21, sub_252_input_limb_22, sub_252_input_limb_23, sub_252_input_limb_24, sub_252_input_limb_25, sub_252_input_limb_26, sub_252_input_limb_27, sub_252_input_limb_28, sub_252_input_limb_29, sub_252_input_limb_30, sub_252_input_limb_31, sub_252_input_limb_32, sub_252_input_limb_33, sub_252_input_limb_34, sub_252_input_limb_35, sub_252_input_limb_36, sub_252_input_limb_37, sub_252_input_limb_38, sub_252_input_limb_39, sub_252_input_limb_40, sub_252_input_limb_41, sub_252_input_limb_42, sub_252_input_limb_43, sub_252_input_limb_44, sub_252_input_limb_45, sub_252_input_limb_46, sub_252_input_limb_47, sub_252_input_limb_48, sub_252_input_limb_49, sub_252_input_limb_50, sub_252_input_limb_51, sub_252_input_limb_52, sub_252_input_limb_53, sub_252_input_limb_54, sub_252_input_limb_55]: [E::F; 56],
        sub_res_limb_0_col0: E::F,
        sub_res_limb_1_col1: E::F,
        sub_res_limb_2_col2: E::F,
        sub_res_limb_3_col3: E::F,
        sub_res_limb_4_col4: E::F,
        sub_res_limb_5_col5: E::F,
        sub_res_limb_6_col6: E::F,
        sub_res_limb_7_col7: E::F,
        sub_res_limb_8_col8: E::F,
        sub_res_limb_9_col9: E::F,
        sub_res_limb_10_col10: E::F,
        sub_res_limb_11_col11: E::F,
        sub_res_limb_12_col12: E::F,
        sub_res_limb_13_col13: E::F,
        sub_res_limb_14_col14: E::F,
        sub_res_limb_15_col15: E::F,
        sub_res_limb_16_col16: E::F,
        sub_res_limb_17_col17: E::F,
        sub_res_limb_18_col18: E::F,
        sub_res_limb_19_col19: E::F,
        sub_res_limb_20_col20: E::F,
        sub_res_limb_21_col21: E::F,
        sub_res_limb_22_col22: E::F,
        sub_res_limb_23_col23: E::F,
        sub_res_limb_24_col24: E::F,
        sub_res_limb_25_col25: E::F,
        sub_res_limb_26_col26: E::F,
        sub_res_limb_27_col27: E::F,
        sub_p_bit_col28: E::F,
        eval: &mut E,
        range_check_9_9_lookup_elements: &relations::RangeCheck_9_9,
    ) -> [E::F; 28] {
        RangeCheckMemValueN28::evaluate(
            [
                sub_res_limb_0_col0.clone(),
                sub_res_limb_1_col1.clone(),
                sub_res_limb_2_col2.clone(),
                sub_res_limb_3_col3.clone(),
                sub_res_limb_4_col4.clone(),
                sub_res_limb_5_col5.clone(),
                sub_res_limb_6_col6.clone(),
                sub_res_limb_7_col7.clone(),
                sub_res_limb_8_col8.clone(),
                sub_res_limb_9_col9.clone(),
                sub_res_limb_10_col10.clone(),
                sub_res_limb_11_col11.clone(),
                sub_res_limb_12_col12.clone(),
                sub_res_limb_13_col13.clone(),
                sub_res_limb_14_col14.clone(),
                sub_res_limb_15_col15.clone(),
                sub_res_limb_16_col16.clone(),
                sub_res_limb_17_col17.clone(),
                sub_res_limb_18_col18.clone(),
                sub_res_limb_19_col19.clone(),
                sub_res_limb_20_col20.clone(),
                sub_res_limb_21_col21.clone(),
                sub_res_limb_22_col22.clone(),
                sub_res_limb_23_col23.clone(),
                sub_res_limb_24_col24.clone(),
                sub_res_limb_25_col25.clone(),
                sub_res_limb_26_col26.clone(),
                sub_res_limb_27_col27.clone(),
            ],
            eval,
            range_check_9_9_lookup_elements,
        );
        VerifyAdd252::evaluate(
            [
                sub_252_input_limb_28.clone(),
                sub_252_input_limb_29.clone(),
                sub_252_input_limb_30.clone(),
                sub_252_input_limb_31.clone(),
                sub_252_input_limb_32.clone(),
                sub_252_input_limb_33.clone(),
                sub_252_input_limb_34.clone(),
                sub_252_input_limb_35.clone(),
                sub_252_input_limb_36.clone(),
                sub_252_input_limb_37.clone(),
                sub_252_input_limb_38.clone(),
                sub_252_input_limb_39.clone(),
                sub_252_input_limb_40.clone(),
                sub_252_input_limb_41.clone(),
                sub_252_input_limb_42.clone(),
                sub_252_input_limb_43.clone(),
                sub_252_input_limb_44.clone(),
                sub_252_input_limb_45.clone(),
                sub_252_input_limb_46.clone(),
                sub_252_input_limb_47.clone(),
                sub_252_input_limb_48.clone(),
                sub_252_input_limb_49.clone(),
                sub_252_input_limb_50.clone(),
                sub_252_input_limb_51.clone(),
                sub_252_input_limb_52.clone(),
                sub_252_input_limb_53.clone(),
                sub_252_input_limb_54.clone(),
                sub_252_input_limb_55.clone(),
                sub_res_limb_0_col0.clone(),
                sub_res_limb_1_col1.clone(),
                sub_res_limb_2_col2.clone(),
                sub_res_limb_3_col3.clone(),
                sub_res_limb_4_col4.clone(),
                sub_res_limb_5_col5.clone(),
                sub_res_limb_6_col6.clone(),
                sub_res_limb_7_col7.clone(),
                sub_res_limb_8_col8.clone(),
                sub_res_limb_9_col9.clone(),
                sub_res_limb_10_col10.clone(),
                sub_res_limb_11_col11.clone(),
                sub_res_limb_12_col12.clone(),
                sub_res_limb_13_col13.clone(),
                sub_res_limb_14_col14.clone(),
                sub_res_limb_15_col15.clone(),
                sub_res_limb_16_col16.clone(),
                sub_res_limb_17_col17.clone(),
                sub_res_limb_18_col18.clone(),
                sub_res_limb_19_col19.clone(),
                sub_res_limb_20_col20.clone(),
                sub_res_limb_21_col21.clone(),
                sub_res_limb_22_col22.clone(),
                sub_res_limb_23_col23.clone(),
                sub_res_limb_24_col24.clone(),
                sub_res_limb_25_col25.clone(),
                sub_res_limb_26_col26.clone(),
                sub_res_limb_27_col27.clone(),
                sub_252_input_limb_0.clone(),
                sub_252_input_limb_1.clone(),
                sub_252_input_limb_2.clone(),
                sub_252_input_limb_3.clone(),
                sub_252_input_limb_4.clone(),
                sub_252_input_limb_5.clone(),
                sub_252_input_limb_6.clone(),
                sub_252_input_limb_7.clone(),
                sub_252_input_limb_8.clone(),
                sub_252_input_limb_9.clone(),
                sub_252_input_limb_10.clone(),
                sub_252_input_limb_11.clone(),
                sub_252_input_limb_12.clone(),
                sub_252_input_limb_13.clone(),
                sub_252_input_limb_14.clone(),
                sub_252_input_limb_15.clone(),
                sub_252_input_limb_16.clone(),
                sub_252_input_limb_17.clone(),
                sub_252_input_limb_18.clone(),
                sub_252_input_limb_19.clone(),
                sub_252_input_limb_20.clone(),
                sub_252_input_limb_21.clone(),
                sub_252_input_limb_22.clone(),
                sub_252_input_limb_23.clone(),
                sub_252_input_limb_24.clone(),
                sub_252_input_limb_25.clone(),
                sub_252_input_limb_26.clone(),
                sub_252_input_limb_27.clone(),
            ],
            sub_p_bit_col28.clone(),
            eval,
        );
        [
            sub_res_limb_0_col0.clone(),
            sub_res_limb_1_col1.clone(),
            sub_res_limb_2_col2.clone(),
            sub_res_limb_3_col3.clone(),
            sub_res_limb_4_col4.clone(),
            sub_res_limb_5_col5.clone(),
            sub_res_limb_6_col6.clone(),
            sub_res_limb_7_col7.clone(),
            sub_res_limb_8_col8.clone(),
            sub_res_limb_9_col9.clone(),
            sub_res_limb_10_col10.clone(),
            sub_res_limb_11_col11.clone(),
            sub_res_limb_12_col12.clone(),
            sub_res_limb_13_col13.clone(),
            sub_res_limb_14_col14.clone(),
            sub_res_limb_15_col15.clone(),
            sub_res_limb_16_col16.clone(),
            sub_res_limb_17_col17.clone(),
            sub_res_limb_18_col18.clone(),
            sub_res_limb_19_col19.clone(),
            sub_res_limb_20_col20.clone(),
            sub_res_limb_21_col21.clone(),
            sub_res_limb_22_col22.clone(),
            sub_res_limb_23_col23.clone(),
            sub_res_limb_24_col24.clone(),
            sub_res_limb_25_col25.clone(),
            sub_res_limb_26_col26.clone(),
            sub_res_limb_27_col27.clone(),
        ]
    }
}
