name: Cairo Prover Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  merge_group:
    types:
      - checks_requested

# On PR events, cancel existing CI runs on this same PR for this workflow.
# Also, create different concurrency groups for different pushed commits, on push events.
concurrency:
  group: >
    ${{ github.workflow }}-
    ${{ github.ref }}-
    ${{ github.event_name == 'pull_request' && 'PR' || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  run-tests:
    runs-on: namespace-profile-starkware-libs-stwo-cairo-xlarge-ubuntu-24-04-amd64
    env:
      NEXTEST_THREADS: "1"
      RUST_MIN_STACK: 4194304
      RUSTFLAGS: -C target-cpu=native
      RUST_LOG_SPAN_EVENTS: enter,close
      RUST_LOG: info
      RUST_BACKTRACE: full
    defaults:
      run:
        working-directory: ./stwo_cairo_prover
    steps:
      - uses: actions/checkout@v6
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - uses: ./.github/actions/setup-repo-rust
      - uses: ./.github/actions/setup-repo-scarb
        with:
          cache: "false"
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Fetch cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: stwo_cairo_prover
      - run: cargo nextest run --cargo-profile witness-opt-1 --features=slow-tests -j ${{ env.NEXTEST_THREADS }} -P ci
      - run: cargo nextest run --cargo-profile witness-opt-1 --features=extract-mem-trace test_serialize_deserialize_mem_trace -j ${{ env.NEXTEST_THREADS }} -P ci
