name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-tests:
    runs-on: stwo-cairo-avx-l
    defaults:
      run:
        working-directory: ./stwo_cairo_prover
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-04-06
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --features="nightly"
