name: Upload-Artifacts

on:
  workflow_dispatch:
  
jobs:
  artifacts-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Get commit hash prefix for PR update
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          echo "SHORT_HASH=${COMMIT_SHA:0:7}" >> $GITHUB_ENV

      - name: Install cross
        run: cargo install cross

      - name: Build all stwo binaries
        run: |
          cd stwo_cairo_prover
          cargo build -r --bin adapted_stwo
          RUSTFLAGS="-C target-cpu=neoverse-v2 -C opt-level=3 -C codegen-units=1 -C target-feature=+sve" cross build --release --target=aarch64-unknown-linux-gnu

      - name: Authenticate with GCS
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.SA_GPS_ARTIFACTS_BUCKET_WRITER_ACCESS_KEY }}

      - name: Upload binary to GCP
        id: upload_file
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "stwo_cairo_prover/target/release/adapted_stwo"
          destination: "adapted_stwo_artifacts/${{ env.SHORT_HASH }}/release"

      - name: Upload ARM binary to GCP
        id: upload_file_arm
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "stwo_cairo_prover/target/aarch64-unknown-linux-gnu/release/adapted_stwo"
          destination: "adapted_stwo_artifacts/${{ env.SHORT_HASH }}/aarch64-release"
